### ISSUE TITLE
ESAS DATA POLICY

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-dev/esas#10]
ESAS DATA MODEL

~The model is available on GitHub (https://github.com/inbo/esas-data-model) and as a webpage (https://inbo.github.io/esas-data-model/tables/). During this transition period, the GitHub repository will be where we maintain and discuss the source version of the ESAS data model. Eventually, the model and its associated vocabularies will be implemented and maintained at ICES.~: The repository is not migrated to ICES: https://github.com/ices-tools-dev/esas/

- [x] The repository is public, but I can grant write access for those that are interested.
- [x] Repository could be moved to ICES GitHub organization. **done**
- [x] Nicolas and I will add the coding files to the repository and/or include them in the field constraints. **done, see #9**
- [x] Anna/Joana will review the current fields and see for which ones ICES vocabularies would be appropriate. Adopting an existing vocabulary will depend on the return of investment (e.g. not map/adopt existing vocab if there is no gain for e.g. analyses). **discussed in #9**
- [x] Since providers will eventually upload data as a single file to ICES, the model might be flattened to represent that. **that is still a good idea**
- [x] Since the model is expressed as a frictionless table schema, data can be validated before uploading. **we have tested this and it works**
- [x] Nicolas R script could help data providers to explore and validate their data **this could be picked up once data submission is possible**

**Comment by peterdesmet** [comment]
- The issue title is/was ESAS DATA POLICY, but ESAS will adopt the ICES data policy and communicate this to its members
- The issue body are notes from a previous meeting. I have annotated those.
