### ISSUE TITLE
JCDP vs ESAS

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-tools-dev/esas#100]
I received an email from Tim Dunn from JNCC... This regarded the possibilities on cetacean data from ESAS flowing into JCDP... My preferred option would be that cetacean data can easily be downloaded from ESAS, and in turn submitted to JCDP. The only feature needed in that case would be the possibility to query cetaceans on the download page. So it would be nice to have such a query with with for example the following options: 
- birds
- cetaceans
- all observations

Not urgent, to be discussed after actual data migration!

**Comment by neil-ices-dk** [comment]
Thanks @nicolasvanermen 

the dataflow would be the other way (Cetaceans interested in ESAS data, not the way you describe). We will take this up on the JCDP gihub

**Comment by peterdesmet** [comment]
@neil-ices-dk any progress on this? Can the issue be closed here?

**Comment by neil-ices-dk** [comment]
@peterdesmet and @nicolasvanermen there is an item on the WGJCDP meeting coming up on the 15th Sept. https://www.ices.dk/news-and-events/meeting-calendar/Pages/ICES-CalendarDisp.aspx?sd=106fc5ba-b653-ec11-9296-00155d2c0c14

Nicolas - not sure if Nikki Taylor (JNCC) has reached out to you, but it could be an idea if you speak with her and/or attend the online WGJCDP meeting.
