### ISSUE TITLE
char() vs nchar() in File Information

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#101]
@cmspinto The [Specification of the format](http://datsu.ices.dk/web/selRep.aspx?Dataset=148) tables use `char(x)` in DataType, but sometimes `nchar(x)`. Is there a difference between the two? If not, can this be updated to `char()` for all?

- [x] Sample > PlatformCode to `char(6)`
- [x] Sample > TargetTaxa to `char(3)`
- [x] Position > Visibility to `char(3)`
- [x] Position > Glare to `char(25)`
- [x] Position > CloudCover to `char(2)`
- [x] Position > Precipitation to `char(2)`

**Comment by cmspinto** [comment]
There is no difference between these, @Osanna123 can you change these? I can try to help if you want.

**Comment by peterdesmet** [comment]
@Osanna123 the updates suggested in this issue can be implemented.

**Comment by Osanna123** [comment]
Types for all fields but PlatformCode are changed in DATSU. The latter is used by multiple projects, and needs additional testing to make sure the change did not affect them
