### ISSUE TITLE
Update constraints of Behaviour, Distance & GroupID fields

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#102]
The [file specification](http://datsu.ices.dk/web/selRep.aspx?Dataset=148) currently has `char(5)` for Behaviour. Since behaviour codes can be combined with ~ that might be too limiting. I would set this to `char(30)` cf. Association.

**Comment by nicolasvanermen** [comment]
I would also set Distance to float 6

- [ ] Distance float(6)
- [ ] Behaviour char(30)

**Comment by peterdesmet** [comment]
@cmspinto can these field length changes be implemented in the database?

@Osanna123 can these field length changes be updated in the [specification of the format](http://datsu.ices.dk/web/selRep.aspx?Dataset=148)

**Comment by neil-ices-dk** [comment]
Anna has tested an import file and it was ok, so fully implemented
