### ISSUE TITLE
Update 3 entries in SamplingMethod vocabulary

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-tools-dev/esas#104]
Regarding the SamplingMethod vocabulary:

1 **Full** ship-based transect method with snapshot for flying birds
2 **Full** ship-based transect method, no snapshot for flying birds
...
5 **Full** ship-based transect method with snapshot for flying birds, but no scan data for outside the transect

The word 'full' does not really have a meaning here, yet this concerns the fact that distance estimation is applied and would better be rephrased as follows:

1 Ship-based transect method with **distance estimation and** snapshot for flying birds
2 Ship-based transect method **with distance estimation**, no snapshot for flying birds
...
5 Ship-based transect method with **distance estimation and** snapshot for flying birds, but no scan data for outside the transect

**Comment by peterdesmet** [comment]
This is now updated on the ESAS docs website: https://esas-docs.ices.dk/tables/#samplingmethod

@Osanna123 3 entries in the official vocab [BD_CountMethod](http://vocab.ices.dk/?ref=1440) should be updated as well:

```
1 Ship-based transect method with distance estimation and snapshot for flying birds
2 Ship-based transect method with distance estimation, no snapshot for flying birds
5 Ship-based transect method with distance estimation and snapshot for flying birds, but no scan data for outside the transect
```

**Comment by peterdesmet** [comment]
@Osanna123 these changes can be implemented in the BD_CountMethod vocabulary.

**Comment by Osanna123** [comment]
done, will be on web-vocab overnight
