### ISSUE TITLE
false status during and after file screening

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-tools-dev/esas#106]
Please see my latest 4 file screenings, there is only 1 erroneous screening (the first test file, screening 114), yet for the other 3 it says 'Screening fisnished, file is not valid to upload to the database'.  The same problem was flagged before for screening 111. 

To frame this: I started new file screenings, because it gave the same remark ('screening finished...') soon after pushing the screening button, and clicking through gave an error message assuming to believe something went wrong. But apparently, the screening was still continuing in the background. Can this be made more clear, with a message stating that the screening is ongoing?

Concluding:
- [ ] Screenings 111, 113, 115 & 116 are OK but status states otherwise
- [ ] While screening is ongoing, status says screening has finished and clicking through gives an error, which is highly confusing!

**Comment by nicolasvanermen** [comment]
![image](https://user-images.githubusercontent.com/7381853/184157896-d3a17101-6e45-4b0a-830f-82366f96ff28.png)

**Comment by nicolasvanermen** [comment]
![image](https://user-images.githubusercontent.com/7381853/184157942-15098fd1-003f-4d4a-909b-cba8827b0919.png)

**Comment by nicolasvanermen** [comment]
![image](https://user-images.githubusercontent.com/7381853/184158076-aa2bc81d-dab9-4f4c-8fe4-e4988e99bd5d.png)

**Comment by nicolasvanermen** [comment]
Printscreens while RSPB datafile is screening (or this is what I assume) - so there is no more false 'screening has finished' message, but no message saying 'screening is ongoing' either, and clicking through gives an error page.

**Comment by cmspinto** [comment]
I belive this has been tackled: 

![image](https://user-images.githubusercontent.com/8705477/185880434-69828025-e652-4c02-ad9c-7d8579fabb73.png)

**Comment by nicolasvanermen** [comment]
No it isn't, see file screening 122, file is valid but no message saying it is, and for files with induced errors there is no message stating it is invalid. Unchecked the bullets in original messages as the issues are either not solved (first bullet) or not checked properly (second bullet)

**Comment by cmspinto** [comment]
![image](https://user-images.githubusercontent.com/8705477/186868787-f4d1f1f1-3a1d-4921-b583-1d6ca931332e.png)

**Comment by nicolasvanermen** [comment]
![image](https://user-images.githubusercontent.com/7381853/186878570-da674239-0952-415b-8672-74f0621f0510.png)

**Comment by cmspinto** [comment]
I think you are correct, in the list of the file screenings there is a discrepancy between some of the messages in the valid files. 
Some have an info message and some don't.
This is a field that is saved to the database when the file is screened.  
I don't know where the discrepancy comes from, it could have to do with the fact if the user waited until de end of the screening.

Will change this field to be calculated in the fly and this way there should be no more discrepancy in the fields.

**Comment by peterdesmet** [comment]
> Will change this field to be calculated in the fly and this way there should be no more discrepancy in the fields.

- [ ] @cmspinto can you notify when this is implemented
- [ ] @Osanna123 can you notify when this is tested as working?

**Comment by cmspinto** [comment]
It's implemented.

**Comment by cmspinto** [comment]
The file screening was now also changed to be asynchronous and a message appears that the file is screening:

**File upload details:**

![image](https://user-images.githubusercontent.com/8705477/188422462-c9b28c8c-0ffb-4f86-9204-b80f6c309fd1.png)


And the list of file(s) screening:

![image](https://user-images.githubusercontent.com/8705477/188422606-42a36807-10bb-4ab3-b56a-6edd2c7764a4.png)

**Comment by neil-ices-dk** [comment]
@Osanna123 can you notify when this is tested as working?

**Comment by Osanna123** [comment]
tested, the status messages look fine
