### ISSUE TITLE
Update description of screening results

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-tools-dev/esas#107]
0For example: https://esas.ices.dk/manage/ScreenResult/116

Please revise this page:

- [x] Edit title: "List of errors and warnings encountered during the screening process:"
- [x] Edit headers of the tabel:"Record line - Type - Message - Value - Field"
- [x] Ideally the list provides filters which would be handy in case of numerous errors and warnings; another option would be that the list can be downloaded (note that long lists of errors and warnings would be avoided by solving [issue 114](https://github.com/ices-tools-dev/esas/issues/114))

**Comment by peterdesmet** [comment]
@Osanna123 or @cmspinto can you make the typo corrections? And report regarding the feasibility to filter on warnings/errors? Perhaps in a separate issue.

**Comment by cmspinto** [comment]
> * Edit headers of the tabel:"Record line - Type - Message - Value - Field"

Can be more than one field and one value.

**Comment by cmspinto** [comment]
> * Ideally the list provides filters which would be handy

Done, the use can now filter from a summary of the errors:

![image](https://user-images.githubusercontent.com/8705477/188580342-966ad2dc-4840-4841-a420-ce3f407d8de1.png)

or

![image](https://user-images.githubusercontent.com/8705477/188580470-e404ed7f-9408-41e3-b543-51e94f8b9bd1.png)

The user just needs to click in the link to filter the table.
