### ISSUE TITLE
Date format in Samples table download

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-tools-dev/esas#109]
The Date in the Samples table download appears as: 1999-07-05T00:00:00
Is there a specific reason why this is not simply  1999-07-05 ?

**Comment by peterdesmet** [comment]
No, there isn't. We requested to change to express the dates as YYYY-MM-DD before, in https://github.com/ices-tools-dev/esas/issues/75#issue-1208507299 and https://github.com/ices-tools-dev/esas/issues/94 (where it was confirmed fix). Have the timestamp returned?

**Comment by peterdesmet** [comment]
The API correctly returns dates as `YYYY-MM-DD` (example: https://esas.ices.dk/api/getCampaignRecords?year=1996)

**Comment by nicolasvanermen** [comment]
FYI: this issue only regards the Samples table, in the Campaigns table the date format is indeed OK.

**Comment by peterdesmet** [comment]
Correct, it is still wrong for Samples in the API as well https://esas.ices.dk/api/getSampleRecords?year=1996

@cmspinto please fix the date format for Samples to `YYYY-MM-DD` in:

- [ ] CSV (download)
- [ ] API

**Comment by peterdesmet** [comment]
@cmspinto this issue can be implemented.
