### ISSUE TITLE
Define Format

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-dev/esas#11]
Need to finalize the format.

- [x] Draft a document with the format (already in the repository)
- [x] Decide on denormalized or normalized format: is ICES mixed record txt file
- [x] Approve the format
- [ ] Approve and insert the vocabularies
- [x] Insert the format in ICES system
- [ ] Add QC Rules based on the present schema
- [ ] Test the files

**Comment by Osanna123** [comment]
[ESAS-ICES format draft.xlsx](https://github.com/ices-tools-dev/esas/files/6364041/ESAS-ICES.format.draft.xlsx)

**Comment by peterdesmet** [comment]
@Osanna123 I wasn't able to download the latest file from the Team chat. Can you drop it here again?

**Comment by Osanna123** [comment]
latest version [ESAS-ICES_format_draft_v1.xlsx](https://github.com/ices-tools-dev/esas/files/6370657/ESAS-ICES_format_draft_v1.xlsx)

also shared in Office.com for joint editing/commenting

**Comment by peterdesmet** [comment]
Format approved at May 3, 2021 meeting. https://ices-tools-dev.github.io/esas/tables/ has been updated to reflect the adopted model.

**Comment by cmspinto** [comment]
Can we close this one?

**Comment by nicolasvanermen** [comment]
Note that there still needed to be some changes to field characterics as well as to field descriptions, but this might be included in another issue?

**Comment by cmspinto** [comment]
It that to change the descriptions of the vocabularies? 
Can that be address in the vocab items?

**Comment by peterdesmet** [comment]
@cmspinto it is an update of the field descriptions (column `Description`) at http://datsu.ices.dk/web/selRep.aspx?Dataset=148 (to make it consistent regarding phrasing, punctuation, etc.). I haven't gotten around to do this yet.

**Comment by cmspinto** [comment]
@Osanna123 could you have a look at this one?
