### ISSUE TITLE
Large datafiles test: milestone

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-tools-dev/esas#110]
The JNCC data cannot be screened because the file is too large. Solution: change the code, or better split up the files?

**Comment by cmspinto** [comment]
Need a bit more description about this issue.

**Comment by nicolasvanermen** [comment]
Simple: I am trying to screen a (large) file and after a short while I receive the error: "The page was not displayed because the request entity is too large."

**Comment by peterdesmet** [comment]
See also this other issue regarding large file errors: https://github.com/ices-tools-dev/esas/issues/108

**Comment by neil-ices-dk** [comment]
@cmspinto to put screening result of largest file (73Mb) 
http://datsu.ices.dk/web/ScreenResult.aspx?sessionid=17973

**Comment by cmspinto** [comment]
This file was now imported to ESAS.

**Comment by neil-ices-dk** [comment]
we would like to retest this but for the species codes (ESAS) some are invalid and therefore need to be corrected in the file before we can reimport; @nicolasvanermen to send a new test file please

**Comment by nicolasvanermen** [comment]
OK, I uploaded a JNCC file with a converted ESAS code in https://drive.google.com/drive/folders/147BaXPO9F8YVG-rLIgQqp_Tj7SJawtll?usp=sharing

**Comment by neil-ices-dk** [comment]
@Osanna123 to test the upload with this file

**Comment by nicolasvanermen** [comment]
Ideally, one more test is performed after the [milestone test](https://github.com/ices-tools-dev/esas/issues/110). I will supply another datafile, including only 2 JNCC campaigns, when uploading this one, and resubmitting 2 campaigns of the first file then there should be two rows in the submissions overview, one row with 11952/11954 campaigns, and one with 2/2 campaigns. Would that be okay for you Anna? (see also https://github.com/ices-tools-dev/esas/issues/67)

**Comment by nicolasvanermen** [comment]
Please see the [shared folder](https://drive.google.com/drive/folders/147BaXPO9F8YVG-rLIgQqp_Tj7SJawtll?usp=sharing):
Original file: ESAS_JNCC_DATA_final_convert6169.csv
Resubmission file with 2 campaigns: ESAS_JNCC_DATA_final_convert6169_resubmission.csv

**Comment by nicolasvanermen** [comment]
A printscreen of the submissions overview would be nice :-)

**Comment by cmspinto** [comment]
Looks like it's working fine :)

![image](https://user-images.githubusercontent.com/8705477/193030346-8957ce15-b958-481b-a083-7473dcf90d6e.png)

**Comment by JochemBoersma** [comment]
Hi Nicolas! (and others..) Good to read that these tests are successful.

Via Rijkswaterstaat (among others: Maarten Platteeuw) I'm the technical data manager of the Wozep Programma, and I have data a project consists of high quality 24 bi-monthly aerial surveys with a lot of bird observations.

It would be very nice if I could use the API to populate the database with our observations, at least as test-case for other data-acquisitions.
Probably better to have contact by mail, instead of this issue-thread.

**Comment by nicolasvanermen** [comment]
@cmspinto 
Just downloaded the JNCC data currently in the database. Since the data are there, I assume the screening was okay. I will do a 'compare' in R to see how the downloaded data fit the file that I shared in the google drive map, as another ultimate test.

**Comment by nicolasvanermen** [comment]
> Hi Nicolas! (and others..) Good to read that these tests are successful.
> 
> Via Rijkswaterstaat (among others: Maarten Platteeuw) I'm the technical data manager of the Wozep Programma, and I have data a project consists of high quality 24 bi-monthly aerial surveys with a lot of bird observations.
> 
> It would be very nice if I could use the API to populate the database with our observations, at least as test-case for other data-acquisitions. Probably better to have contact by mail, instead of this issue-thread.

Hello @JochemBoersma , is this the same data that are managed by Bureau Waardenburd. At least I am in contact with Job de Jong & Ruben Fijn regarding the upload of the MWTL data.

**Comment by neil-ices-dk** [comment]
Anna also tested large file and all fine
