### ISSUE TITLE
Disclaimer in download

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-tools-dev/esas#111]
- [x] edit: http://gis.ices.dk/geonetwork/srv/eng/catalog.search#/metadata/7a6151e4-812b-4455-97a2-74c5102d418f
- [x] edit: (description on this link: http://datsu.ices.dk/web/selRep.aspx?Dataset=148)
- [x] edit: Data provided from the website are classified as either 'Public' or 'Restricted':
- [x] edit: better to move "Documentation can be found at https://esas-docs.ices.dk/" to section 3

**Comment by peterdesmet** [comment]
I assume these are typos/suggestions for the `disclaimer.txt` file that is included in a download. @neil-ices-dk can you correct these or is this something for @cmspinto?

**Comment by neil-ices-dk** [comment]
>  edit: (description on this link: http://datsu.ices.dk/web/selRep.aspx?Dataset=148)

the typo in the dataset name has been forwarded to the vocab management group for correcting

>  edit: (description on this link: http://datsu.ices.dk/web/selRep.aspx?Dataset=148)

do you want the description to be the full text from the landing page? 
https://www.ices.dk/data/data-portals/Pages/European-Seabirds-at-sea.aspx

> edit: better to move "Documentation can be found at https://esas-docs.ices.dk/" to section 3

this was previously moved from section 3 to gather the links in one section and a pointer made in section 3 to avoid repetition:
_Information about the ESAS data and formats can be found in the links in section 7._

**Comment by nicolasvanermen** [comment]
There are two links in section 3 already... so still preferring the https://esas-docs.ices.dk/ in section 3 as well.

**Comment by nicolasvanermen** [comment]
Regarding the 2nd bullet, the link should only be between brackets: 
The Download ZIP bundle includes the requested data file in the CSV format (description on this link: 
 http://datsu.ices.dk/web/selRep.aspx?Dataset=148), and the data disclaimer.  

The Download ZIP bundle includes the requested data file in the CSV format (description on this link) 
 http://datsu.ices.dk/web/selRep.aspx?Dataset=148, and the data disclaimer.  
...instead of...
The Download ZIP bundle includes the requested data file in the CSV format (description on this link: 
 http://datsu.ices.dk/web/selRep.aspx?Dataset=148), and the data disclaimer.

**Comment by neil-ices-dk** [comment]
typo corrected in vocab; @nicolasvanermen it would be easier if you go and make the edits on the disclaimer yourself and then just ping Carlos who will upload the final version - thanks
https://github.com/ices-tools-dev/esas/blob/main/disclaimer-download

**Comment by nicolasvanermen** [comment]
OK did so, the first commit gave some sort of warning though:
![image](https://user-images.githubusercontent.com/7381853/191435330-0682d8a7-90c1-4725-b4ba-8317e5b69a72.png)

**Comment by peterdesmet** [comment]
@nicolasvanermen you can ignore the warning you got: your next commit got a ✔️ meaning that the website (https://esas-docs.ices.dk/) was built successfully.

**Comment by neil-ices-dk** [comment]
@cmspinto to pull into the esas app

**Comment by cmspinto** [comment]
Disclaimer updated, could someone `have a look?

**Comment by neil-ices-dk** [comment]
@cmspinto yes the disclaimer matches, there is one issue though in section 6

> Additionally, if the download is predominantly from one or two data providers, please directly acknowledge the data source(s) when using the data:
XXXXXXXXXXXXXXXXXXXX

Where XXXX was supposed to be filled with the DataRightsHolder(s)

**Comment by peterdesmet** [comment]
I have updated the disclaimer document at https://github.com/ices-tools-dev/esas/blob/main/disclaimer-download. Note that it includes a number of whitespace changes that I think make the text easier to read, so please replace the entire disclaimer.

I have also updated the citation sentence to:

> A minimum citation would include the following:
> 
> European Seabirds At Sea (ESAS) (https://esas.ices.dk), 2022. ICES, Copenhagen
> 
> If the download is predominantly from one or two data providers, please acknowledge them directly as well.
> The following data providers contributed to the download:
> 
> XXXXXXXXXXXXXXXXXXXX

**Comment by nicolasvanermen** [comment]
I have a long history of misinterpreting this specific issue, but as far as I understand now XXXXXXXXX will be a tailored list of data providers included in the download, and this is what will be implemented. Correct me if I am wrong again...

**Comment by peterdesmet** [comment]
> but as far as I understand now XXXXXXXXX will be a tailored list of data providers included in the download

Yes, that is how I understood it too.

**Comment by neil-ices-dk** [comment]
@cmspinto to include the data providers to each disclaimer (the XXXXX bit)

**Comment by cmspinto** [comment]
Haven't publish yet, will do tomorrow (28/10/2022) but the citation will look like this:

![image](https://user-images.githubusercontent.com/8705477/198313623-5af59a3c-1c93-4464-81e4-9a903d33d49a.png)

Disclaimer:
![image](https://user-images.githubusercontent.com/8705477/198313938-fbdfcda6-4acb-49a6-9a5a-911241f1d612.png)

**Comment by nicolasvanermen** [comment]
The current disclaimer in the download includes the institutes names, yet is not the same as the one reviewed by Peter: https://github.com/ices-tools-dev/esas/blob/main/disclaimer-download.
So parallel versions are circulating apparently...

**Comment by cmspinto** [comment]
Have updated the disclaimer to be this one: https://github.com/ices-tools-dev/esas/blob/main/disclaimer-download

**Comment by nicolasvanermen** [comment]
Beautiful, closing this issue.
