### ISSUE TITLE
edmo code for DHI A/S

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-tools-dev/esas#112]
Currently there is no edmo code for the company DHI A/S, which has been suggested as DRH for the Ornis Consult data (Ornis Consult does not exist anymore). Can a new code be made available?

**Comment by nicolasvanermen** [comment]
Or maybe better for the mother group DHI, as I have difficulties in finding reference to DHI A/S...: [dhigroup.com](url)

**Comment by peterdesmet** [comment]
@nicolasvanermen what is the relationship between DHI (A/S) and Ornis Consult?
- Is DHI completely replacing Ornis Consult and should historical records be associated with and managed by DHI (cf. how we lumped a bunch of old codes into NIOZ)
- Or should historical records be kept with Ornis Consult [5440](https://edmo.seadatanet.org/report/5440) and new records be associated with DHI? In which case we need two data rights holders that are going to respond to issues.

**Comment by nicolasvanermen** [comment]
The exact relationship is unclear to me, the first option is what was requested by Henrik Skov. Anyhow, it seems a bit strange to have data 'owned' by a non-existing organisation (although the data will be public).

**Comment by nicolasvanermen** [comment]
First option, all under the flag of DHI

**Comment by peterdesmet** [comment]
@Osanna123 what information do you need to create a new EDMO?

**Comment by Osanna123** [comment]
DHI in Hørsholm is registered with the EDMO code 740 (https://edmo.seadatanet.org/report/740)
Please let me know if you need an EDMO code for the DHI in Aarhus. Then i'll send a respective request to maris

**Comment by peterdesmet** [comment]
@nicolasvanermen do we want a new DHI (Aarhus) or an existing DHI in Hørsholm (https://edmo.seadatanet.org/report/740)?

**Comment by nicolasvanermen** [comment]
I would prefer a (new) code for the overarching DHI as the existing one
refers to a sub-division.

**Comment by peterdesmet** [comment]
Great, seems like we should use 740 then. I'll update the documentation so that Ornis Consult becomes DHI 740

**Comment by nicolasvanermen** [comment]
OK, I see, 740 is indeed the right code for DHI. But since Henrik Skov agreed to set the data public, we can hold on to the original DRH, i.e. Ornis Consult. Closing this somewhat confusing issue.
