### ISSUE TITLE
Unknown (0) in Behaviour

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-tools-dev/esas#113]
Related to[ issue 70](https://github.com/ices-tools-dev/esas/issues/70), any reason why we chose to keep this value?

**Comment by nicolasvanermen** [comment]
Same goes for code 99 in prey type...

**Comment by nicolasvanermen** [comment]
Strangely, code zero is in the [vocabulary ](http://vocab.ices.dk/?ref=1709)but gives an error in the screening of the ORNIS data.

**Comment by peterdesmet** [comment]
## Behaviour

- Code `0` not listed on the documentation website https://esas-docs.ices.dk/tables/#behaviour
- Code `0` is available in the [official vocabulary](http://vocab.ices.dk/?ref=1709), but it is not associated with ESAS (hence why you get an error when screening)

@Osanna123 can you confirm code `0` for behaviour is used by other non-ESAS databases? If not, it can likely be removed from the vocabulary.

**Comment by Osanna123** [comment]
I think it was decided at the beginning to reduce all the codes with descriptions 'unknown' to a single one. In case of the Behaviour, it became 0. I think i mapped inly the 'valid' codes to the ESAS dataset. Now, after reading this thread, i'm not sure whether Behaviour 0 should be linked to ESAS or not. Please advise

**Comment by peterdesmet** [comment]
`unknown` isn't used for any ESAS vocab (https://esas-docs.ices.dk/tables/), so I think the intent is to not allow this value for ESAS. I would therefore remove the link with ESAS for Behaviour `0`.

**Comment by neil-ices-dk** [comment]
Unknown is not mapped to ESAS http://vocab.ices.dk/?CodeID=249778

The relationships between the dataset and code values for behaviour are here: 
http://vocab.ices.dk/?CodeTypeRelID=1709&CodeID=235388

So we need to update the DATSU links accordingly.
@cmspinto to take this with @mehdiabbasi

**Comment by cmspinto** [comment]
Soon it will be implemented in RECO a new feature to filter a vocab using a code type to find the relationship.
This will then be implemented in DATSU links.

**Comment by neil-ices-dk** [comment]
closing and opening new ticket for the relations vocab issue
