### ISSUE TITLE
Use `ZZ99` for unknown PlatformCode

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-tools-dev/esas#114]
I would prefer the PlatformCode field no longer to be required, it always gives an long list of warnings due to deprecated code ZZ90...

**Comment by peterdesmet** [comment]
@cmspinto Rather, is it possible to not warn for deprecated PlatformCode in the file screening?

**Comment by cmspinto** [comment]
@peterdesmet, the short answer is no, these messages are generated by DATSU.
We need to ask @Osanna123  if there is any code that is not deprecated that can be used.

**Comment by nicolasvanermen** [comment]
Now that it is possible to filter the screening results this issue has low priority. But a non-deprecated code (we already tried AA30 before) would still be handy...

**Comment by peterdesmet** [comment]
@Osanna123 recommends: use `ZZ99` to avoid deprecation warning.

**Comment by peterdesmet** [comment]
@nicolasvanermen to close issue when changed in data providing side

**Comment by peterdesmet** [comment]
The use of ZZ99 for unknown is now recommended in the docs: b37c6ee
