### ISSUE TITLE
Checks on Latitude-Longitude & Distance-Area & links between tables

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-tools-dev/esas#115]
- [x] Values outside the specified range should give errors in case of Latitude and Longitude
- [x] There should be a cross check for Distance & Area (at least one should hold a positive value)
- [x] Turning Distance into float(6) should coincide with a specified range Lower:0.000100000000 Upper: 9999.000000000000, as in Area #102
- [x] There should be a check of the links between the tables (are all CampaignID's in Samples present in Campaigns, etcetera...) (see [issue 117](https://github.com/ices-tools-dev/esas/issues/117) and file screening 128)

**Comment by peterdesmet** [comment]
@Osanna123 can you implement these checks? Would be good that they are implemented before testing the full upload.

**Comment by peterdesmet** [comment]
Should also be tested with a file that purposefully contains errors (cf. #117).

**Comment by neil-ices-dk** [comment]
Anna is working on this, in progress

**Comment by neil-ices-dk** [comment]
Implemented; tested but @Osanna123 to test "Values outside the specified range should give errors in case of Latitude and Longitude"

**Comment by Osanna123** [comment]
done
