### ISSUE TITLE
Area values quoted in csv download

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-tools-dev/esas#116]
For some reason Area values are quoted in the csv download, as opposed to the other numeric fields Latitude, Longitude and Distance. Any reason why?

**Comment by cmspinto** [comment]
Good catch, that is corrected now, Area is numeric.

**Comment by nicolasvanermen** [comment]
@peterdesmet can you check this in the API? (if relevant)

**Comment by peterdesmet** [comment]
I can't verify, the API returns a 500 error code: https://esas.ices.dk/api/getPositionRecords

@cmspinto is this expected?

**Comment by cmspinto** [comment]
No, it was not expected. Have re-publish the API and should be working now.

**Comment by peterdesmet** [comment]
I can't test this as fixed, because the database contains no data. @cmspinto or @Osanna123 can you notify me when there is data? I'll assign this issue to me for testing.

**Comment by neil-ices-dk** [comment]
there is now a datafile loaded; esas.ices.dk needs to be reloaded, will be online by 12:00 13th Sep
![image](https://user-images.githubusercontent.com/23527005/189860728-bd82f63a-910e-42f4-ad68-7dfe6dd4e353.png)

**Comment by peterdesmet** [comment]
API returns 500 error code again: https://esas.ices.dk/api/getPositionRecords

**Comment by peterdesmet** [comment]
Confirmed that area has unquoted numeric values in API and CSV.
