### ISSUE TITLE
Failed to screen a file with introduced errors

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-tools-dev/esas#117]
See title, no file screening results (error page) for file screening 126, although the file itself is there.

**Comment by cmspinto** [comment]
There was a bug and it was pointing to a null when it tried to check if it was a re-submission.

Corrected now it will be published during today:

![image](https://user-images.githubusercontent.com/8705477/185859592-5d293c4f-9a90-4da3-a85d-e5ac2a56a9f2.png)

**Comment by nicolasvanermen** [comment]
OK I screened a comparable file and now it got through immediately... So now I got a list of the induced errors, except for a very important one! I induced a SampleID which is not present in Positions. The other way around: there is SampleID in Positions which is not in Samples. This should give a fatal error. How come it is not checked?

**Comment by nicolasvanermen** [comment]
See new bullet in [issue 115](https://github.com/ices-tools-dev/esas/issues/115)

**Comment by peterdesmet** [comment]
Closing this issue in favour of #115 where a check in relations between files is requested.
