### ISSUE TITLE
Escape commas for vocabulary download

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#119]
This is probably larger than ESAS, but the CSV download for vocabularies (and likely other places) do not escape commas in field values. This breaks the tabular format of the data. Example:

1. Go to http://vocab.ices.dk/?ref=1687
2. Click the CSV button and accept the download conditions
3. Open the csv file ([RECO_Export_05-01-2022-12-01-05.csv](https://github.com/ices-tools-dev/esas/files/9488903/RECO_Export_05-01-2022-12-01-05.csv))
4. See how commas in the definitions break the column format:

<img width="851" alt="Screenshot 2022-09-05 at 12 12 07" src="https://user-images.githubusercontent.com/600993/188425502-60152659-4eeb-4878-ace6-f4ee89b09986.png">

**Ideally, an existing csv library should be used to deal with these issue by escaping (wrapping "in quotes") such values.** This also doesn't affect users that rely on comma as delimiter.

If that is not possible, **I suggest using tab-delimiters for all CSV downloads throughout ices.dk** (tabs are far less likely to occur in fields). The files can still be called `csv` in my opinion. Note that this change might affect users with workflows that expect comma as delimiter, but not escaping commas is an issue that cannot be ignored, because it is very hard to fix for users downstream.

PS: I'm hereby obliging "Data Users are obliged to inform ICES of any suspected problems in the data." 😄

**Comment by neil-ices-dk** [comment]
@peterdesmet fair point, will put something on the vocab governance group and then see if we can book some time to fix this issue

**Comment by mehdiabbasi** [comment]
@peterdesmet @neil-ices-dk @cmspinto Thank you Peter for spotting this issue. It is fixed now and CSV download works with text including commas. 
![image](https://user-images.githubusercontent.com/38282276/188581505-f8ebc4d3-eab7-4b4d-bf21-2ac2a2e5fbce.png)
