### ISSUE TITLE
Define Vocabularies

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-dev/esas#12]
Define the format vocabularies

This issue is linked with #11.

**Comment by cmspinto** [comment]
Some of the codes need to be translated from the ESAS Vocabularies to ICES vocabularies. 

Need to identity what vocabularies can't be replicated in ICES, examples:

- Provider -> [EDMO Code](https://vocab.ices.dk/?ref=1398)

**Comment by peterdesmet** [comment]
These are now separated in issues (see https://github.com/ices-tools-dev/esas/milestone/1). @cmspinto I will add your suggested vocabs in the relevant issues. Note that there is no field `country`.
