### ISSUE TITLE
file screening email

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-tools-dev/esas#123]
We regret to inform you that your submission is not compliant with the European Seabirds At Sea (ESAS) data format and therefore **it was not** uploaded to the database.
Please rephrase to:
We regret to inform you that your submission is not compliant with the European Seabirds At Sea (ESAS) data format and therefore **it can not be** uploaded to the database.

**Comment by nicolasvanermen** [comment]
In the new email format:
Thank you for submitting SeaBird data -> Thank you for submitting seabird data

**Comment by cmspinto** [comment]
Done both.

**Comment by nicolasvanermen** [comment]
I now seem to receive two confirmation emails for the same file screening... Small bug?
One with sender 'File Screening', and one with sender 'European Seabirds At Sea'

**Comment by nicolasvanermen** [comment]
This bug seems to be solved (only one email with sender 'File Screening')
The email text should still be adapted:
We regret to inform you that your submission is not compliant with the European Seabirds At Sea (ESAS) data format and therefore **it was not** uploaded to the database.
Please rephrase to:
We regret to inform you that your submission is not compliant with the European Seabirds At Sea (ESAS) data format and therefore **it can not** be uploaded to the database.

**Comment by cmspinto** [comment]
It is already **can not** be uploaded

![image](https://user-images.githubusercontent.com/8705477/203747306-547a2315-892e-40d2-8548-d8571462c855.png)

**Comment by nicolasvanermen** [comment]
Not in the emails that I am receiving...
![image](https://user-images.githubusercontent.com/7381853/203751028-81c4e130-3c14-499a-bfad-b1053446257d.png)

**Comment by cmspinto** [comment]
Found it thanks:

![image](https://user-images.githubusercontent.com/8705477/203766499-30b2329a-ed9d-42ad-99bc-61d5f0c5e403.png)

**Comment by nicolasvanermen** [comment]
Great, thanks, I just love to close Github issues!
