### ISSUE TITLE
500 error for API

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#126]
I am currently getting a 500 error for the API: https://esas.ices.dk/api/getCampaignRecords

**Comment by nicolasvanermen** [comment]
@peterdesmet:
Can you check? I received the same error using the application, but this was quickly solved, hoping this is also the case for the API.

**Comment by peterdesmet** [comment]
I'm no longer getting a 500, so closing this issue. Now that there's lots of data, the API response is rather slow. I'm reopening the ticket on API pagination.
