### ISSUE TITLE
 AccessionID [20222859]

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-tools-dev/esas#127]
At 3h46 I received an email stating:  
The file (ESAS_BE_DATA_final.csv [FileID:201]) was inserted into the database correctly.

At 4h22 I received an email stating: 
We are sorry to report that there was an issue inserting the file (ESAS_BE_DATA_final.csv) with Accession 20222859 into the database.
You screening file id is 201.

Watskebeurt?

**Comment by nicolasvanermen** [comment]
Less alarming but strange nevertheless: for AccessionID [20222862]  I received to seperate emails stating the data was inserted correctly.

**Comment by JochemBoersma** [comment]
> Watskebeurt?

more information about this phrase: https://en.wikipedia.org/wiki/Watskeburt

**Comment by nicolasvanermen** [comment]
All screenings en submissions since October 18 went well! Closing this issue.
