### ISSUE TITLE
DATSU overflow error

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-tools-dev/esas#128]
![image](https://user-images.githubusercontent.com/7381853/195371034-d072667c-566b-44d5-871a-6a94538b26ee.png)

**Comment by nicolasvanermen** [comment]
![image](https://user-images.githubusercontent.com/7381853/195371888-f95c295f-efb0-4ba0-a173-66fa3b06ddb0.png)

**Comment by cmspinto** [comment]
> The screening reports the double amount of rows compared to what was originally submitted... There is only 1 file record row, 827 campaign rows, etc. Resulting it says that there are duplicates in every ID! How is that possible?

That should not be possible and there is unfortunately not a logic explanation (at least we can't find it). 
Our solution was to restart the server and now we only allow one file to be process at the time!
We put several ESAS files yesterday and it took some time but all were screen correctly. 

Please have a look: [http://datsu.ices.dk/web/ListSessions.aspx?Dataset=148](http://datsu.ices.dk/web/ListSessions.aspx?Dataset=148)

**Comment by nicolasvanermen** [comment]
All screenings en submissions since October 18 went well! Closing this issue.
