### ISSUE TITLE
file submission email

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-tools-dev/esas#129]
Also `Our team will check with happend` rather than `happened`

_Originally posted by @peterdesmet in https://github.com/ices-tools-dev/esas/issues/124#issuecomment-1276299063_

**Comment by nicolasvanermen** [comment]
![image](https://user-images.githubusercontent.com/7381853/195375486-9f38a422-64a5-4f05-973b-8755b1ad5480.png)

**Comment by cmspinto** [comment]
The subject of the message was now updated to ESAS (AccessionID [xxxxxxxxx])

**Comment by nicolasvanermen** [comment]
OK copy that. Not checked because all submissions went fine this week! Closing this issue.
