### ISSUE TITLE
Upload of the Data

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-dev/esas#13]
All data can be uploaded to the database using a submission facility.

**Comment by peterdesmet** [comment]
Indeed, @nicolasvanermen has received all data from the old JNCC database (v5) and converted those to the current data model (that we call v6). That consists of 3 related csv files:

file | records
--- | ---:
`trips.csv` | 23962
`positions.csv` | 1514080
`observations.csv` |  2696460

Those can be uploaded through the new submit facility

**Comment by nicolasvanermen** [comment]
Actually, apart from implementing the new data model, ESAS v6.0 is the
result of merging ESAS v5 with the Belgian, Dutch and German updates
(implying an 10% increase in the number of positive observations compared
to ESAS v5). We hope to include Dutch aerial surveys soon as well, but
there appears to be some bureaucratic bottleneck regarding data ownership...

**Comment by peterdesmet** [comment]
Closing this issue, as we need to do quite a lot of testing beforehand. The idea is to:

- Submit the data either via UI or API, so it passes QA
- Split the data into files by data provider and year, so it is easier to track the progress
