### ISSUE TITLE
API returns samples from restricted campaigns

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#132]
This is a restricted campaign: https://esas.ices.dk/api/getCampaignRecords?campaignID=19910813112

```json
[
  {
    "tblUploadID": 232,
    "tblCampaignID": 209012,
    "dataRightsHolder": "5045",
    "country": "NL",
    "campaignID": "19910813112",
    "dataAccess": "Restricted",
    "startDate": "1991-08-13",
    "endDate": "1991-08-13",
    "notes": null
  }
]
```

- [x] It assume it is normal that I (public user) can query for the existence of this campaign? @nicolasvanermen 
- [x] I should probably not be able to query for samples within this campaign? @nicolasvanermen Currently I can: https://esas.ices.dk/api/getSampleRecords?campaignID=19910813112 @cmspinto can you fix this?
- [x] I cannot query for positions in the campaign, which is expected: https://esas.ices.dk/api/getPositionRecords?campaignID=19910813112
- [x] I cannot query for observations in the campaign, which is expected: https://esas.ices.dk/api/getObservationRecords?campaignID=19910813112

**Comment by nicolasvanermen** [comment]
I don't think this has ever been talked through but besides from that I am not against being able to query for restricted data sample records... I might give some insight in the type of data (platform type, counting method, ...) which in turn may determine whether not to request data.

**Comment by peterdesmet** [comment]
But what do you the data owners of such data expect? I think it is clearer to communicate that only campaign info is publicly available?

**Comment by nicolasvanermen** [comment]
Yes that is indeed more straightforward.

**Comment by peterdesmet** [comment]
@cmspinto can you implement this as such (don’t return samples from restricted campaigns).

**Comment by cmspinto** [comment]
Fixed, thanks for the heads up. This was a bug in the getSamples for the API. 
[https://esas.ices.dk/api/getSampleRecords?campaignID=19910813112](https://esas.ices.dk/api/getSampleRecords?campaignID=19910813112)
