### ISSUE TITLE
'delete' button in file screening page?

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-tools-dev/esas#134]
Would it be easy to add a 'delete' button in the file screening page? Especially for test files or large erroneous files it seems a bit crazy to keep those in the list...

**Comment by cmspinto** [comment]
Yes, this can be done.

**Comment by cmspinto** [comment]
It will not be possible to delete the files that have been uploaded to the database:

![image](https://user-images.githubusercontent.com/8705477/199194621-4a4d243d-ff39-47a5-abe0-13595f0ecf2b.png)

**Comment by nicolasvanermen** [comment]
Great, thanks!
