### ISSUE TITLE
citation text

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-tools-dev/esas#138]
The ICES librarian has asked if we would adjust the citation to conform to the standard format. 

from:
European Seabirds At Sea (ESAS) (2022). ICES, Copenhagen. https://esas.ices.dk/

To:
European Seabirds at Sea (ESAS). 2022. ICES, Copenhagen, Denmark. https://esas.ices.dk/

ok with this?

**Comment by nicolasvanermen** [comment]
Sure!

**Comment by neil-ices-dk** [comment]
thank you, and done!

**Comment by peterdesmet** [comment]
I've also requested an update at https://www.vliz.be/imis?module=dataset&dasid=3117
