### ISSUE TITLE
missing WoRMS codes

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-tools-dev/esas#139]
New ESAS taxa that are missing in WoRMS (EURING ID between parenthesis):

- [x] Elanus caeruleus (02350): https://marinespecies.org/aphia.php?p=taxdetails&id=1718415
- [x] Hieraaetus pennatus (02980): https://marinespecies.org/aphia.php?p=taxdetails&id=1484453
- [x] Apus pallidus (07960): https://marinespecies.org/aphia.php?p=taxdetails&id=1718417
- [x] Apus affinis (08000): https://marinespecies.org/aphia.php?p=taxdetails&id=1718419
- [x] Apus sp. (08009): https://www.marinespecies.org/aphia.php?p=taxdetails&id=206119

All recent changes to the list: https://github.com/ices-tools-dev/esas/compare/6ddbe7a38c78158b887b068489bbf2066b7dd576...main

**Comment by peterdesmet** [comment]
@nicolasvanermen Apus sp. is available in worms, see updated above.

**Comment by peterdesmet** [comment]
Aphia IDs received and added to https://esas-docs.ices.dk/species/
