### ISSUE TITLE
Review trips: data_provider

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#15]
`trips: data_provider` indicates the data provider with an integer code:

https://github.com/ices-tools-dev/esas/blob/0d294b4ea678e34f52409a16602f9133ac179dcf/_data/table-schemas/trips.yaml#L20-L50

- [x] @ices-tools-dev/data-and-information Should this field be part of the data **yes** or should a data provider be selected (dropdown) when uploading (limiting one upload to one provider)?
- [x] @ices-tools-dev/data-and-information Does ICES already have a list of data providers?

**Comment by peterdesmet** [comment]
The second question is answered in https://github.com/ices-tools-dev/esas/issues/12#issuecomment-737909821, where it was suggested to use [EDMO code](https://vocab.ices.dk/?ref=1398), which also uses integer values. I will try to map these.

**Comment by nicolasvanermen** [comment]
I would keep the data provider field inside the database, to allow a clear
link to the data origin for data users.

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by Osanna123** [comment]
agree

**Comment by Osanna123** [comment]
Missing EDMO codes are added to the google doc

**Comment by peterdesmet** [comment]
Thanks @Osanna123. With that, all known ESAS organizations now have EDMO codes (8ca0967). Closing issue.
