### ISSUE TITLE
Review trips: platform_type

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#16]
`trips: platform_type` indicates the platform type with an integer code:

https://github.com/ices-tools-dev/esas/blob/0d294b4ea678e34f52409a16602f9133ac179dcf/_data/table-schemas/trips.yaml#L102-L108

- [x] @ices-tools-dev/data-and-information Does ICES already have a controlled vocabulary for this? **yes**
- [x] @nicolasvanermen Wouldn't human readable values like `ship` be better, or are the integer codes well established?

**Comment by peterdesmet** [comment]
@HjalteParner:

> @peterdesmet, yes ICES already have a platform code vocabulary including platform type or class if you like.
> 
> Please have a look at ICES platform code request system at http://vocab.ices.dk/request for details.

**Comment by peterdesmet** [comment]
ICES platform class could be valuable indeed: https://vocab.ices.dk/?ref=311 Here's my attempt at mapping:

esas code | esas value | ices code | value
--- | --- | --- | ---
1 | Ship | 30 | Ship
2 | Helicopter | 67 | Helicopter
3 | Aeroplane | 62 | aeroplane
4 | Aeroplane (digital survey) | ? | ?

@nicolasvanermen can you explain what a digital survey is? If we can find/add a suitable value for that, I propose we use the ICES vocabulary here.

**Comment by nicolasvanermen** [comment]
Only 4 values, and unlikely that there will be many future additions, so
human-readable values would be ok by me.

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
@nicolasvanermen that means we can probably easily adopt ICES vocab here. Can you give a bit more explanation about what a "Aeroplane (digital survey)" is?

**Comment by nicolasvanermen** [comment]
Digital surveys use cameras, the images or videos are analysed afterwards.

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
@nicolasvanermen I notice that the fact that it is a digital survey is already captured in `count_method`:

https://github.com/ices-tools-dev/esas/blob/0d294b4ea678e34f52409a16602f9133ac179dcf/_data/table-schemas/trips.yaml#L213-L214

Can I suggest we drop it here? Then we can easily use the ICES vocab.

**Comment by nicolasvanermen** [comment]
Yes we can.

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
Ok! @ices-tools-dev/data-and-information or @HjalteParner, what values should we use in the provided data:

```
30
67
62
```

Or:

```
ship
helicopter
aeroplane
```

I would prefer the latter, as it is easier to understand without context.

**Comment by nicolasvanermen** [comment]
The latter please.


Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
This is now updated: https://ices-tools-dev.github.io/esas/tables/#platform_type

@ices-tools-dev/data-and-information let us know if providing these values (`aeroplane`, `ship`, `helicopter`) will work.

**Comment by Osanna123** [comment]
I had the same comment for the aeroplane (digital survey) that it merges platform type and observation method, good you covered it in the discussion above.
Providing codes is more preferable, but we can map descriptions to the codes in the DB @cmspinto please confirm.

**Comment by cmspinto** [comment]
This is the only thing I found similar: https://vocab.ices.dk/?ref=14

**Comment by peterdesmet** [comment]
These are the updated human readable values ESAS will use:

https://github.com/ices-tools-dev/esas/blob/77b9faf016e03c650c0e80ade37f6162470d0f9e/_data/table-schemas/trips.yaml#L102-L116
