### ISSUE TITLE
Review trips: count_method

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#18]
`trips: count_method` indicates the count method with an integer code:

https://github.com/ices-tools-dev/esas/blob/0d294b4ea678e34f52409a16602f9133ac179dcf/_data/table-schemas/trips.yaml#L200-L215

- [x] @ices-tools-dev/data-and-information Does ICES already have a controlled vocabulary for this? **yes, but values need to be added**
- [x] @nicolasvanermen Wouldn't human readable values like `all_obs` be better, or are the integer codes well established?

**Comment by nicolasvanermen** [comment]
I would hold on to the integer codes, count methods can only be described
in rather drawn-out sentences.

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by Osanna123** [comment]
This would have to be reviewed more carefully. At ICES, we have related vocabs BD_CountMethod https://vocab.ices.dk/?ref=1440 and SMTYP https://vocab.ices.dk/?ref=152 that could be used to adopt this reference list

Code 13 would better fit into species_counted

**Comment by peterdesmet** [comment]
Will be added as new ICES vocabulary, ESAS prefers to keep using integer codes.

**Comment by nicolasvanermen** [comment]
Code 13 is a strange one indeed, and has been used during 11 trips in the
current ESAS v6.0. As suggested by Anna this should be moved to
'species_counted', leaving the 'count_method' field empty until it can be
specified further (by those who have collected these data or alternatively
by looking into the observation table itself and try to figure out what
method was used...).

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
Move `13 Only cetaceans and rare birds` to `species_counted` as `18` and leave other values as is (integers).

**Comment by Osanna123** [comment]
All vocab suggestions would have to pass through the ICES Reference Management Group, which is focusing on reusing the existing concepts.
