### ISSUE TITLE
Review trips: species_counted

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#19]
`trips: species_counted` indicates what species are counted with an integer code:

https://github.com/ices-tools-dev/esas/blob/0d294b4ea678e34f52409a16602f9133ac179dcf/_data/table-schemas/trips.yaml#L235-L255

- [x] @ices-tools-dev/data-and-information Does ICES already have a controlled vocabulary for this? **No**
- [x] @nicolasvanermen Wouldn't human readable values like `all`, `all_not_larus` be better, or are the integer codes well established?

**Comment by nicolasvanermen** [comment]
I would hold on to the integer codes, species_counted often gets drawn-out
descriptions.

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by Osanna123** [comment]
need new vocab

**Comment by Osanna123** [comment]
Question: what does 'All species' mean?

**Comment by nicolasvanermen** [comment]
This means that all species encountered are counted, opposed to the other
codes that all indicate a selection of species (not) being counted.

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582
