### ISSUE TITLE
Review trips: use_of_binoculars

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#20]
`trips: use_of_binoculars` indicates whether binoculars were used with an integer code:

https://github.com/ices-tools-dev/esas/blob/0d294b4ea678e34f52409a16602f9133ac179dcf/_data/table-schemas/trips.yaml#L292-L297

- [x] @ices-tools-dev/data-and-information Does ICES already have a controlled vocabulary for this? **No**
- [x] @nicolasvanermen Wouldn't human readable values like `no`, `yes_far` be better, or are the integer codes well established?

**Comment by nicolasvanermen** [comment]
I would hold on to the integer codes (drawn-out descriptions).

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by Osanna123** [comment]
need new vocab
