### ISSUE TITLE
Review trips: behaviour_recording

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#21]
`trips: behaviour_recording` indicates the behaviour recording with an integer code:

https://github.com/ices-tools-dev/esas/blob/0d294b4ea678e34f52409a16602f9133ac179dcf/_data/table-schemas/trips.yaml#L307-L313

- [x] @ices-tools-dev/data-and-information Does ICES already have a controlled vocabulary for this? **No**
- [x] @nicolasvanermen Wouldn't human readable values like `ship_based`, `other` be better, or are the integer codes well established?

**Comment by nicolasvanermen** [comment]
I would hold on to the integer codes (drawn-out descriptions).

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by Osanna123** [comment]
need new vocab

**Comment by cmspinto** [comment]
Hi @peterdesmet, would it be a good idea to keep the issues open if they need a new vocab?

We have a github to approve vocabularies, maybe we can link our approval wiht the original ticket here, does this make sense @neil-ices-dk and @Osanna123 ?
