### ISSUE TITLE
Review trips: platform_side

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#22]
`trips: base_side` indicates the used side of the platform with an integer code:

https://github.com/ices-tools-dev/esas/blob/0d294b4ea678e34f52409a16602f9133ac179dcf/_data/table-schemas/trips.yaml#L324-L333

- [x] @ices-tools-dev/data-and-information Does ICES already have a controlled vocabulary for this? **No**
- [x] @nicolasvanermen Wouldn't human readable values like `aerial_right_front` be better, or are the integer codes well established?

**Comment by nicolasvanermen** [comment]
Human-readable values would be OK for me, can all be described in a concise
and unambiguous manner.

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
@nicolasvanermen Something like this? Suggestions welcome:

new label | old label
--- | ---
right_front | 1 Aerial survey: right front 
left_back | 2 Aerial survey: left back 
right_back | 3 Aerial survey: right back 
left_front | 4 Aerial survey: left front 
left | 5 Ship-based survey: port side 
right | 6 Ship-based survey: starboard side 
both_sides | 9 Observers

**Comment by nicolasvanermen** [comment]
Looks good to me.

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
@nicolasvanermen can we also rename this field to `platform_side`?

**Comment by nicolasvanermen** [comment]
Sure!

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
See https://ices-tools-dev.github.io/esas/tables/#platform_side, I have:

- Updated the field name to `platform_side`
- Moved the field up, so it appears directly after `platform_type` and `platform_code`
- Used space in the labels: `right back`, `both sides`

**Comment by Osanna123** [comment]
need new vocab
Note for this and other reference lists, codes don't matter much, we can make human-readable descriptions instead of codes in the data input template and the data output, if wanted

**Comment by peterdesmet** [comment]
Updated values ESAS will use:

https://github.com/ices-tools-dev/esas/blob/77b9faf016e03c650c0e80ade37f6162470d0f9e/_data/table-schemas/trips.yaml#L164-L173
