### ISSUE TITLE
Review trips: observer_role

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#24]
`trips: observer_role` indicates the observer role with an integer code:

https://github.com/ices-tools-dev/esas/blob/0d294b4ea678e34f52409a16602f9133ac179dcf/_data/table-schemas/trips.yaml#L368-L374

- [x] @ices-tools-dev/data-and-information Does ICES already have a controlled vocabulary for this? **no**
- [ ] @nicolasvanermen What is the use of this field? Is it when there are concurrent observations on two sides of a platform? Is it possible that both are primary then?

**Comment by nicolasvanermen** [comment]
When there are two concurrent observations (two independent data streams),
one gets the primary role, the other the secondary. In case only one data
stream should be used, this should be the one collected by the primary
observer. Alternatively we could use values such as big boss and little
boss.

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
@nicolasvanermen do you have cases of "triple observer platform"? And is it important to know the difference between stream 2 and 3 or are they considered equal (but of lesser importance than 1).

Wouldn't it be clearer if we have a boolean field (TRUE/FALSE) called `primary_data_stream`?

**Comment by nicolasvanermen** [comment]
This should be discussed with Nele, this is a new field, and not familiar
with the use of it.

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by Osanna123** [comment]
Need for a new vocab at ices.
Few more questions regarding the observer-role:
1. in the Trip table, it looks like fields from base_side to observer role can be reported multiple times for the same tripkey. is it correct? If yes, they might need to go a level lower to 'position' or get a separate record.
2. are these 3 roles duplicating(triplicating) each other (like recording same colonies, from the same position on the platform), or complementing each other?

**Comment by peterdesmet** [comment]
With us potentially dropping the observer fields, I wonder if the usefulness of this field is under discussion. We need to figure that out first. 😄

**Comment by nicolasvanermen** [comment]
Even when dropping the observer field, this field would still be needed to
indicate whether a data stream is primary or secondary in case of double
observer platform counts.

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
Discussed with @ericstienen and @nicolasvanermen and decided to drop this field. When there are concurrent data streams, there are better fields like `platform_side` to decided what is useful for analysis.

Done in bd6ffe4. Closing issue, as the field should not be added to the model.
