### ISSUE TITLE
Review positions: glare

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#27]
`positions: glares` indicates the glare with an integer code:

https://github.com/ices-tools-dev/esas/blob/0d294b4ea678e34f52409a16602f9133ac179dcf/_data/table-schemas/positions.yaml#L186-L192

- [x] @ices-tools-dev/data-and-information Does ICES already have a controlled vocabulary for this? **no**
- [x] @nicolasvanermen Wouldn't human readable values like `no`, `weak` be better, or are the integer codes well established?

**Comment by nicolasvanermen** [comment]
OK to use no, weak, medium & strong as values. But nevertheless there
should still be a lookup table to further clarify these codes (e.g. medium
= "a part of the viewing area is affected by glare").

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by Osanna123** [comment]
need new vocab

will it ever be useful?

**Comment by peterdesmet** [comment]
Glare has been updated in 8f19338 to use the human readable values:

```
none
weak
medium
strong
```

**Comment by peterdesmet** [comment]
@nicolasvanermen do we need glare AND visibility?

**Comment by nicolasvanermen** [comment]
Yes please!

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582
