### ISSUE TITLE
Review positions: cloud_cover

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#28]
`positions: cloud_cover` indicates the cloud cover with an integer octa code:

https://github.com/ices-tools-dev/esas/blob/0d294b4ea678e34f52409a16602f9133ac179dcf/_data/table-schemas/positions.yaml#L213-L221

- [x] @ices-tools-dev/data-and-information Does ICES already have a controlled vocabulary for this? Are octas used as well? **no**

**Comment by Osanna123** [comment]
need new vocab
