### ISSUE TITLE
Review positions: precipitation

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#29]
`positions: precipitation` indicates the precipitation with an integer code:

https://github.com/ices-tools-dev/esas/blob/0d294b4ea678e34f52409a16602f9133ac179dcf/_data/table-schemas/positions.yaml#L223-L228

- [x] @ices-tools-dev/data-and-information Does ICES already have a controlled vocabulary for this? **no**
- [x] @nicolasvanermen Wouldn't human readable values like `rain`, `fog` be better, or are the integer codes well established?

**Comment by nicolasvanermen** [comment]
Yes, OK to use human-readable values here.

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by Osanna123** [comment]
need new vocab
Personally, i have doubts about usefulness of this field and the 'glare' in any future assessments/estimates.
It seems like 'visibility' alone would have been more useful

**Comment by peterdesmet** [comment]
Update in db80fc2 to use human-readable values.

**Comment by peterdesmet** [comment]
Implemented: positions have a `Precipitation` field.
