### ISSUE TITLE
Review positions: observation_quality

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#30]
`positions: observation_quality` indicates the observation quality with an integer code:

https://github.com/ices-tools-dev/esas/blob/0d294b4ea678e34f52409a16602f9133ac179dcf/_data/table-schemas/positions.yaml#L249-L254

- [x] @ices-tools-dev/data-and-information Does ICES already have a controlled vocabulary for this? **yes, on data quality: https://vocab.ices.dk/?ref=342**
- [x] @nicolasvanermen Wouldn't human readable values like `good` be better, or are the integer codes well established?

**Comment by nicolasvanermen** [comment]
Yes, human readable values are fine here.

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by Osanna123** [comment]
as a recognized standard, i would suggest a SeaDataNet quality flagging: https://vocab.ices.dk/?ref=342

**Comment by peterdesmet** [comment]
Hi @Osanna123 the term name might be a bit of a misnomer. It describes the general observation conditions in the field (e.g. visibility), not necessarily the quality of the data which is what https://vocab.ices.dk/?ref=342 describes.

@nicolasvanermen how is this field used in analysis?

**Comment by nicolasvanermen** [comment]
This is a newly induced field, favoured at least by FTZ and Bureau
Waardenburg. Depending on the objectives, it can be used to select high
quality data prior to further analysis. It can also be used as a covariate
in distance analysis, so the detection function may change accordingly.

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
> it can be used to select high quality data prior to further analysis

So it is an indication of data quality?

**Comment by nicolasvanermen** [comment]
Primarily it is a subjective assessment of the observation conditions, but
clearly, in turn this relates to data quality as well.

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
Rename to `observation_conditions`

**Comment by peterdesmet** [comment]
Updated in c4ab027440915fd2bcaaca82ba449006d921fcbd:

https://github.com/ices-tools-dev/esas/blob/c4ab027440915fd2bcaaca82ba449006d921fcbd/_data/table-schemas/positions.yaml#L240-L253

**Comment by peterdesmet** [comment]
Implemented: positions have a `ObservationConditions` field.
