### ISSUE TITLE
Review observations: transect

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#31]
`observations: transect` indicates the transect with an integer code:

https://github.com/ices-tools-dev/esas/blob/0d294b4ea678e34f52409a16602f9133ac179dcf/_data/table-schemas/observations.yaml#L30-L35

- [ ] @ices-tools-dev/data-and-information Does ICES already have a controlled vocabulary for this?
- [x] @nicolasvanermen Wouldn't human readable values like `inside` be better, or are the integer codes well established?

**Comment by nicolasvanermen** [comment]
OK for me. What do you suggest for value 3? "outside_alt"? Again along with
a description in a separate lookup table or the data model?

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
@nicolasvanermen Can you explain what "Out of transect and of 90 deg scan" is exactly?

**Comment by nicolasvanermen** [comment]
No, we have gone over this before, nobody seems the know exactly...

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
If nobody knows, can't we simplify this to a boolean field `in_transect`:

- TRUE = `2` Inside transect
- FALSE =  `1` Out of transect  and `3` Out of transect and of 90 deg scan

**Comment by nicolasvanermen** [comment]
This was Mark Lewis' opinion on this: "don’t know – BUT, there was talk of
allowing observers to record things that were practically on the transect
line – but marginally on the wrong side of it. Something to do with the
beleif that observers like to reward themselves by making observations.
This code would allow them to record these birds (thus, reward) but allow
the data to be filtered out later."

Maybe best to simply lump it with "outside of transect"

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
> Maybe best to simply lump it with "outside of transect"

Yes, absolutely. Can we rename to `in_transect` then (name suggestions welcome), with boolean values?

**Comment by nicolasvanermen** [comment]
Boulean is OK. There is no need to change the field name though.

**Comment by peterdesmet** [comment]
Great! Updated in 200946c, with `TRUE` meaning **in** transect.

**Comment by peterdesmet** [comment]
I think this can be closed.
