### ISSUE TITLE
Review observations: age_class

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#33]
`observations: age_class` indicates the age class with a letter or integer code:

https://github.com/ices-tools-dev/esas/blob/0d294b4ea678e34f52409a16602f9133ac179dcf/_data/table-schemas/observations.yaml#L146-L159

- [ ] @ices-tools-dev/data-and-information Does ICES already have a controlled vocabulary for this?

**Comment by Osanna123** [comment]
This looks like a combination of 2 concepts - maturity and age, the latter is usually expressed as integers at ICES

**Comment by peterdesmet** [comment]
Discussed this with @nicolasvanermen and would like to keep this as is. Splitting the field would complicate things.

**Comment by Osanna123** [comment]
ICES Reference Management Group would have problems with keeping it as is.

**Comment by nicolasvanermen** [comment]
Could you elaborate on that? Personally I have my doubts with the moult information in this column, but the age information is highly relevant and in my opinion very transparent coding.

**Comment by peterdesmet** [comment]
Implemented: observations have a `LifeStage` field.
