### ISSUE TITLE
Review observations: plumage

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#34]
`observations: plumage` indicates the plumage with a letter code:

https://github.com/ices-tools-dev/esas/blob/77b9faf016e03c650c0e80ade37f6162470d0f9e/_data/table-schemas/observations.yaml#L168-L190

- [x] @ices-tools-dev/data-and-information Does ICES already have a controlled vocabulary for this? **no**

**Comment by Osanna123** [comment]
Need new vocab

Plumage types:
•	B Breeding (summer) plumage
•	T Transient plumage (moulting between winter & summer plumage or vice-versa)
•	W Non-breeding (winter) plumage
•	L Light morph (skuas/double light ‘LL’ fulmars)
•	C Coloured morph (‘L’, ‘D’ & ‘DD’ fulmars)
•	I Intermediate morph (skuas)
•	D Dark morph (skuas)
•	P Pullus
For immature auks (Guillemot & Razorbill):
•	A1 ½ or less than adult size
•	A2 Over ½ adult size
•	A3 About same size as adult
For immature Northern Gannets:
•	G1 Plumage 1
•	G2 Plumage 2
•	G3 Plumage 3
•	G4 Plumage 4
•	G5 Plumage 5

**Comment by peterdesmet** [comment]
I updated the issue body so it links to the current vocab.

**Comment by Osanna123** [comment]
Brief description or reference to a publication for what f.ex. "‘L’, ‘D’ & ‘DD’ fulmars" or "Plumage 1-5" in Northern gannets means would be beneficial.
As i understand, LL and DD are not valid codes, right?

**Comment by nicolasvanermen** [comment]
All these mainly refer to traditional ways of coding, only described by means of drawings actually. The gannet codes were kept on explicit demand of the ESAS community. Despite this, future data submissions should ideally only use age coding for gannets, and distinguish between light and coloured morphs for fulmars.
