### ISSUE TITLE
Review observations: sex

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#35]
`observations: sex` indicates the sex with an integer code:

https://github.com/ices-tools-dev/esas/blob/0d294b4ea678e34f52409a16602f9133ac179dcf/_data/table-schemas/observations.yaml#L220-L230

- [x] @ices-tools-dev/data-and-information Does ICES already have a controlled vocabulary for this? I assume it does, are the values `F` and `M` used? **Yes, and the codes are the same**
- [x] @nicolasvanermen is unknown sex always indicated as an empty value? I'm fine with this, it's just that this differs with other fields which have a separate value for unknown.

**Comment by nicolasvanermen** [comment]
For most fields "unknown" should be indicated by a missing value,
apparently it did stick in the distance and direction_of_travel_type
fields...

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
Ok, I will add a remark to those fields.

**Comment by Osanna123** [comment]
so far suggesting SEXCO https://vocab.ices.dk/?ref=45

**Comment by peterdesmet** [comment]
Closing this issue, since the ESAS values map the SEXCO https://vocab.ices.dk/?ref=45 already and no action is required.
