### ISSUE TITLE
Review observations: direction_of_travel

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#36]
`observations: direction_of_travel` indicates the direction of travel with a letter code:

https://github.com/ices-tools-dev/esas/blob/0d294b4ea678e34f52409a16602f9133ac179dcf/_data/table-schemas/observations.yaml#L241-L255

- [ ] @ices-tools-dev/data-and-information Does ICES already have a controlled vocabulary for this?
- [x] @nicolasvanermen Wouldn't it be better to express all of this as degrees from north (e.g. heading)? Or are the number reserved for heading relative to the platform?

**Comment by nicolasvanermen** [comment]
Yes, during aerial surveys direction of travel is often recorded relative
to the movement of the plane.

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
@nicolasvanermen I think this should be clearer defined in the definition, so that numbers **always** represent headings relative to the movement of the plane. My attempt:

> Cardinal direction in which the bird/cetacean is travelling:
> ...
> Direction relative to the movement of the platform (plane/ship) in which the bird/cetacean is travelling as degrees in increments of 10°:
> ...

Agree?

**Comment by peterdesmet** [comment]
Oh, my mistake, the type of direction (relative or absolute) is indicated in `direction_of_travel_type` (#23). I that case I think we can always work with numeric values? With `U Flying, no apparent direction` being expressed as an empty value?

**Comment by nicolasvanermen** [comment]
OK, with a minor suggestion:

(Inter)cardinal direction in which the bird/cetacean is travelling:
...
Direction relative to the movement of the platform (plane/ship) in which
the bird/cetacean is travelling as degrees in increments of 10°:
...

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by nicolasvanermen** [comment]
Let's keep this in, for some data providers (that do not use the U, W, F
codes in the distance column), this might be the only column indicating
flight behaviour. It also means more than unknown direction, personally I
would interpret this as 'hanging around', 'attached to the area',... for
what it's worth.

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
To make this less confusing on a database level can we decide to:

- [ ] Only record whether this is absolute or relative directions in the `direction_of_travel_type` field?
- [ ] Only allow `0` to `360` values?
- [ ] Converting `N` to `0`, `NE` to `45`
- [ ] Replace `U` by empty, but convince data providers to populate `distance` instead if they don't?

**Comment by nicolasvanermen** [comment]
I am not a fan - code U becomes the odd only letter code, only because
you're dropping the (inter)cardinal codes N, NE, ..., U, which are widely
used in the ESAS v6 (though they were coded as integers 0-10, with 0 for no
data, 1 for no apparent direction, 2 for N and so on, that was confusing!).

**Comment by peterdesmet** [comment]
Ok, agree to leave the codes as is. Final question:

1. Do we assume the N, NW, E values to always be absolute?
2. Do we assume the 0, 10, 20 values to always be relative?

If so, there is no need for a `direction_of_travel_type` field in trips.

**Comment by nicolasvanermen** [comment]
That's more or less the way it has been recorded up until now. I would
leave all options open however. N, NE, ... NW are clearly absolute,
direction in degrees can in theory be both, so it would be best to keep the
direction_of_travel_type.

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
> direction in degrees can in theory be both

Could you check if that is the case in the data you currently have? I'd very much prefer to contain all the necessary info in just this field.

**Comment by nicolasvanermen** [comment]
OK Peter, but note that we already dropped 4 (yet unused) codes without
consulting the parties that originally included these codes, which is fine
because they can be added to the controlled vocabulary if wanted. Which
will not be possible once the field is dropped fully. This should all have
been discussed earlier...

**Comment by peterdesmet** [comment]
After conversation with @nicolasvanermen: opted for N, NE, ... as absolute and 0, 10, 20 as relative directions. We therefore no longer need `direction_of_travel_type`. See 5e1decc.

**Comment by peterdesmet** [comment]
Implemented: observations have a `TravelDirection` field.
