### ISSUE TITLE
Review observations: prey

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#37]
`observations: prey` indicates the prey with an integer code:

https://github.com/ices-tools-dev/esas/blob/0d294b4ea678e34f52409a16602f9133ac179dcf/_data/table-schemas/observations.yaml#L308-L380

- [x] @ices-tools-dev/data-and-information Does ICES already have a controlled vocabulary for this? **No**
- [x] @nicolasvanermen I notice a lot of unknown values. How likely is it these will be assigned to an actual value? Should we merge them into one? Also, wouldn't human readable values like `fish` be better, or are the integer codes well established?

**Comment by nicolasvanermen** [comment]
Same as for platform code, some might still be translated or decoded in the
future. Originally I proposed to simply delete all unknown codes as a
thorough clean-up, but this had little support from the ESAS community,
with information loss as their main argument. Though of course unknown
codes are as uninformative as empty fields, keeping them leaves all options
open.

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by Osanna123** [comment]
need new vocab.
We have a similar concept Stomach_Item in the pipeline for Stomach DB

**Comment by nicolasvanermen** [comment]
add codes
28: Eel
29: Pipefish
44: Shore crab (Carcinus Maenas)

**Comment by peterdesmet** [comment]
These codes have been added to the documentation website in f9a5b20 (with correct lowercase for `maenas`), but @Osanna123 the codes still have to be added to http://vocab.ices.dk/?ref=1687

**Comment by peterdesmet** [comment]
Implemented: observations have a `Prey` field, with full vocab.

**Comment by nicolasvanermen** [comment]
Codes still to be added:
28: Eel
29: Pipefish
44: Shore crab (Carcinus maenas)

**Comment by peterdesmet** [comment]
Thanks @Osanna123! When will these new codes show up in the list http://vocab.ices.dk/?ref=1687
