### ISSUE TITLE
Review observations: association

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#38]
`observations: association` indicates the association with an integer code:

https://github.com/ices-tools-dev/esas/blob/0d294b4ea678e34f52409a16602f9133ac179dcf/_data/table-schemas/observations.yaml#L457-L515

- [x] @ices-tools-dev/data-and-information Does ICES already have a controlled vocabulary for this? **no**
- [x] @nicolasvanermen Wouldn't human readable values be better, or are the integer codes well established? I also notice a lot of unknown values: how likely is it that these will be assigned?

**Comment by nicolasvanermen** [comment]
Best to hold on to the integers, a long list with sometimes drawn out
descriptions.

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by Osanna123** [comment]
need new vocab and a bit more info on these references

**Comment by Osanna123** [comment]
comments from RMG:
only one Unknown will be accepted
code 200 needs translation
What does the MSFA stand for?
codes 57, 58 need explanation

**Comment by nicolasvanermen** [comment]
- only one Unknown will be accepted: OK, we will transform all unknown
   codes to missing values, so a code for Unknown will no longer be necessary
   - code 200 needs translation: Flying between (turbine) foundations
   - What does the MSFA stand for? Multi-Species Feeding Association
   - codes 57, 58 need explanation Reviewed in Camphuysen & Webb 1999


Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
Removed unknown codes + added explanation in 3cc4e97.

**Comment by nicolasvanermen** [comment]
OK, I left the codes in the database itself though, leaving the chance for them to be explained by the data providers.

**Comment by nicolasvanermen** [comment]
Add codes:
100: Association with set nets
101: Association with fish trap
103: Next to sandbank

**Comment by peterdesmet** [comment]
Updated in documentation website 9c84028 (using `Associated` rather than `Association` to be consistent with other definitions). @Osanna123 still to be added to http://vocab.ices.dk/?ref=1718

**Comment by peterdesmet** [comment]
Implemented: observations have a `Association` field, with full vocab.
