### ISSUE TITLE
Public availability flag

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#4]
@cmspinto:

> Sorry, just a small comment,
> I think that the easiest way to manage would be if the flag is to the whole submission.
> Sorry I thought that we clear that during the meeting!
> Note: Let me know if you see any case where it would be better to put the data acess flag in a lower level.

That could work, but the flag itself should be stored at trip level in the database, so we can support use cases like these:

1. Submit 2012-2018 data from INBO, submission is marked private.
2. Noticed an error in the 2016 data onwards, submit new batch of 2016-2018 INBO data, replacing stored data. Decide it can be all public now.
3. Decide that 2012-2015 data (which were not updated) can be public too. Login and mark as such.
3. Submit 2019-2020 data from INBO, upload is marked private.

End result: 2012-2018 data public, 2019-2020 data private.

I think it would be easier to separate submissions from public/private flags. You submit data and it falls under the privacy settings for that provider, e.g. all data older than a year is public (note this is how it is implemented at Movebank and has proven useful).

**Comment by peterdesmet** [comment]
Note that the format now has a flag at trip level:

https://github.com/ices-tools-dev/esas/blob/0d294b4ea678e34f52409a16602f9133ac179dcf/_data/table-schemas/trips.yaml#L85-L92

**Comment by Osanna123** [comment]
Flag at a trip level is ok. 
As a standard approach, we have a standard reference list Data_access (https://vocab.ices.dk/?ref=1435) with options public/restricted.

**Comment by peterdesmet** [comment]
Ok, then I suggest to rename the term to `data_access` and have the values `public` and `restricted`

**Comment by peterdesmet** [comment]
Note, the field is now called `public_data` as a boolean:

https://github.com/ices-tools-dev/esas/blob/67c038cf02d6884aac6bd8cb9554b740c79159c9/_data/table-schemas/trips.yaml#L79-L86

**Comment by peterdesmet** [comment]
Implemented.
