### ISSUE TITLE
Review observations: behaviour

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#40]
`observations: behaviour` indicates the behaviour with an integer code:

https://github.com/ices-tools-dev/esas/blob/0d294b4ea678e34f52409a16602f9133ac179dcf/_data/table-schemas/observations.yaml#L600-L682

- [x] @ices-tools-dev/data-and-information Does ICES already have a controlled vocabulary for this? **no**
- [x] @nicolasvanermen Wouldn't human readable values like `feeding_young` be better, or are the integer codes well established? I also notice a lot of unknown values: how likely is it that these will get assigned?

**Comment by nicolasvanermen** [comment]
Best to hold on to the integers, a long list with sometimes drawn out
descriptions.

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by Osanna123** [comment]
need a new vocab

**Comment by Osanna123** [comment]
Comments from RMG:
we can not keep 'Unknown' with many codes
we need info on the codes 121-123
additional description is needed, including relevance to species groups

**Comment by nicolasvanermen** [comment]
*We will transform all unknown codes to missing values, so a code for Unknown will no longer be necessary
*121: Milling / Non-directional behaviour
*122: Diving (marine mammals)
*123: Head out of water (seals)

**Comment by peterdesmet** [comment]
The `unknown` codes have been removed and the definitions for 121-123 updated: e37aa7f

**Comment by nicolasvanermen** [comment]
OK, I left the codes in the database itself though, leaving the chance for them to be explained by the data providers.

**Comment by nicolasvanermen** [comment]
FYI: there are still unknowns in the behaviour field.

**Comment by peterdesmet** [comment]
Oh, you are right, I removed the unknown codes for prey (where I think that can be done too). I now removed them for behaviour in 7dbfca6.

**Comment by peterdesmet** [comment]
Implemented: observations have a `Behaviour` field, with full vocab.
