### ISSUE TITLE
Commas are not escaped in csv export

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#41]
Didn't really know in what repository to report this, but when downloading EDMO codes from https://vocab.ices.dk/?ref=1398 in csv file, I noticed that commas are not escaped, which then conflicts with the comma as separator:

```
tblCodeID,Code,Description,tblCodeTypeID,CodeType,Created,Modified,Deprecated
144695,1,University of Birmingham, Department of Geological Sciences,1398,EDMO,2015-02-06,2020-09-28,True
144704,10,University of Liverpool, Oceanographic Laboratories, Department of Earth Sciences,1398,EDMO,2015-02-06,2020-09-28,False
144794,100,Leibniz Institute for Baltic Sea Research Warnemünde (IOW),1398,EDMO,2015-02-06,2020-09-28,False
```

Resulting in:

tblCodeID | Code | Description | tblCodeTypeID | CodeType | Created | Modified | Deprecated
--- | --- | --- | --- | --- | --- | --- | ---
144695 | 1 | University of Birmingham |  **Department of Geological Sciences** | 1398 | EDMO | 2015-02-06 | 2020-09-28 | True
144704 | 10 | University of Liverpool |  **Oceanographic Laboratories** |  **Department of Earth Sciences** | 1398 | EDMO | 2015-02-06 | 2020-09-28 | False
144794 | 100 | Leibniz Institute for Baltic Sea Research Warnemünde (IOW) | 1398 | EDMO | 2015-02-06 | 2020-09-28 | False

The correct way would be to offer the csv with `"..."` for values containing commas:

```
tblCodeID,Code,Description,tblCodeTypeID,CodeType,Created,Modified,Deprecated
144695,1,"University of Birmingham, Department of Geological Sciences",1398,EDMO,2015-02-06,2020-09-28,True
144704,10,"University of Liverpool, Oceanographic Laboratories, Department of Earth Sciences",1398,EDMO,2015-02-06,2020-09-28,False
144794,100,Leibniz Institute for Baltic Sea Research Warnemünde (IOW),1398,EDMO,2015-02-06,2020-09-28,False
```

I haven't tested, but if the same csv module is used for all data exports, it probably occurs for data other than EDMO as well.

**Comment by cmspinto** [comment]
Hi Mehdi,

Do you think this is a bug?
Either put ";", tabs, or replace the commas by "..." or otherwise the user who downloads the file will not be able use it!

**Comment by peterdesmet** [comment]
Note that selecting another delimiter `;` or tab could divert the problem (in case those values occur in fields). And I assume you didn't meant _replace_ the commas, but merely wrapping values with commas in quotes (also note that `"` in those values have to be double escaped).

This kind of issues are handled by default by most csv export libraries (I don't know what tool/software is used to generate the ICES csvs though :smile:)

**Comment by cmspinto** [comment]
We are not using a tool. It is programmed in C#, so the program reads the dateset/query and outputs it in a text file.

**Comment by peterdesmet** [comment]
Then tab as delimiter is probably your safest choice, as these are generally harder to write into input fields than `,` or `;`.

**Comment by nicolasvanermen** [comment]
This issue is also relevant for the uploads, so flagging this here. I cannot upload files in which the fields are quoted, resulting in potential problems with commas in the Notes fields. Up until now I avoided this problem by doing...
**OBSERVATIONS$Notes <- gsub(",", ";", OBSERVATIONS$Notes)**
...thus replacing commas by ";". As Peter flagged, this is not future proof, and likely to give problems when multiple data providers try to upload their data.

**Comment by peterdesmet** [comment]
@cmspinto did you close this issue because it is resolved (in RECO) or because it was in the wrong repository?

**Comment by cmspinto** [comment]
Because it is in Reco and not in ESAS
@mehdiabbasi will have a look at Reco this summer and this could be an issue he can tackle.
