### ISSUE TITLE
Add trip:data_provider_country field

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#43]
Add an field to indicate the (sub) country of the data provider, for credit purposes. Country information has always been included in ESAS data, but as part of the trip key.

@Osanna123 what ISO codes can be used? https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes. Level 1 and/or 2. 2 or 3 letter?

**Comment by peterdesmet** [comment]
I don't fully understand why `data_provider` and `data_provider_country` need to be submitted. Since `data_provider`s are linked to EDMO, can't country information be stored there? https://vocab.ices.dk/?CodeID=144872 That would avoid conflicts such as:

```
data_provider, data_provider_country
220, BE
220, NL
```

Both record are from INBO, but one says INBO is from BE while the other says INBO is from NL.

**Comment by Osanna123** [comment]
We use 3 excerpt lists from ISO-3166, including 2-alpha codes, country sub-divisions, and deleted/former country references.
The reference list: https://vocab.ices.dk/?ref=337
In theory, it is possible to pick the country reference from the EDMO code, but there are a few points against it:

- normally the field is easy to report, and it is often used in data filters (in the download interface and the downloaded data)
- included in the format, reporting allows using regions, if needed (Scotland, Azores, etc.)
- If the field is derived from EDMO, it will not be present in the 'raw' data, but considered a data product. We can also consider an option of this field auto-filled based on an EDMO reference, if regions and previous countries are not needed.

EDMO code 220 is not valid, code 202 is linked to Belgium. If an organisation has several offices or labs, they can be registered in EDMO separately.

**Comment by peterdesmet** [comment]
Decided to add this field https://ices-tools-dev.github.io/esas/tables/#country

> Country or region that should be associated with this campaign. Uses the ISO-3166 vocabulary.

Since there currently is no use case for providers to set this field, it can be autofilled based on the EDMO codes. Since multiple EDMO codes are possible, multiple country codes are possible as well.

**Comment by peterdesmet** [comment]
Implemented: file information has a `Country` field, using ISO codes.
