### ISSUE TITLE
Add vernacular_name or scientific_name

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#46]
To retain the original identification, add a string value of the species, either as a `vernacular_name` or `scientific_name` field.

**Comment by nicolasvanermen** [comment]
Since there is no vernacular name in ESAS v6.0, do we leave this empty in
historical data??

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
No, we should include it (by mapping it to the species list). Otherwise we will lose any reference.

**Comment by peterdesmet** [comment]
Hmm, in most cases it would probably be better to have the originally recorded `scientific_name` as a reference. But if we name the field `scientific_name` then values such as the following are a bit odd for that field:

```
Pterodroma feae / madeira / deserta
Phalacrocorax sp.
unidentified Storm Petrel
unidentified dabbling duck
patterned dolphin
unidentified fish school
```

Would it be better if we call it `species_name`, with it's equivalent `species_code`?

**Comment by nicolasvanermen** [comment]
OK

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
Done in c4ab027.

**Comment by Osanna123** [comment]
Is it worth mentioning in the description that the field is checked against the lookup table?

**Comment by peterdesmet** [comment]
As I understood it, the `SpeciesCode` will be checked against a reference table, the `SpeciesName` would not. It serves as a verbatim reference to how the species were recorded in the local system.

**Comment by nicolasvanermen** [comment]
How would you fill this in for historical data? I suggest to leave it empty as the holabird table (species reference table) evolved through time, with in the end different versions circulating .

**Comment by peterdesmet** [comment]
Since the newly added field `SpeciesCodeType` https://ices-tools-dev.github.io/esas/tables/#speciescodetype can potentially allow `Non-taxonomic based ID` there is no need for a full written vernacular/scientific name.
