### ISSUE TITLE
Rename number to count

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#47]
@nicolasvanermen, I would like to rename `number` to `count` for individuals counted. I have encountered the term `count` or `individualCount` (e.g. in [Darwin Core](http://rs.tdwg.org/dwc/terms/individualCount)) much more for this attribute and I think it would be good to align it. Would that be ok?

**Comment by nicolasvanermen** [comment]
OK

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582
