### ISSUE TITLE
Data policy references broken link

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#48]
Under 4d, the [ICES data policy](https://www.ices.dk/data/Documents/ICES-Data-policy.pdf) references https://www.ices.dk/datacentre/Submissions/ but that results in a 404.

**Comment by peterdesmet** [comment]
Another broken link: http://ices.dk/marine-data/maps/Pages/default.aspx).

**Comment by neil-ices-dk** [comment]
all resolved
