### ISSUE TITLE
Review trips: do we need "route"

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#49]

**Comment by nicolasvanermen** [comment]
In my opinion we don't need this at the level of an ICES ESAS database, a bit the same as transect_id (closed issue #7)

**Comment by peterdesmet** [comment]
Then I would suggest to remove this field.

**Comment by Osanna123** [comment]
Current description for the 'Route' is 'Short description of the area covered or route followed.'
Can this field be limited to a reference list? 
Is there a reason to have it as a separate optional, free-text field, rather than suggesting to include this information in the Notes?

**Comment by peterdesmet** [comment]
Field removed, description of `notes` expanded to:

https://github.com/ices-tools-dev/esas/blob/1191578770fe2a152068bf5d41f267efb94d7681/_data/table-schemas/trips.yaml#L305-L308
