### ISSUE TITLE
Do we need TripKey in Observations

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#52]
The relation between the tables is:

> observation -> position -> trip

Meaning that observations have a `PosKey` and positions have a `TripKey`. @Osanna123 you mentioned that it is also necessary to add `TripKey` to observations (which I have done), but can you explain why this is necessary, as it can lead to inconsistencies:

```
TRIP A
TRIP B
POS X: TRIP A
POS Y: TRIP B
OBS 1: POS X, TRIP A
OBS 1: POS X, TRIP B <- incorrect direct link to TRIP
```

**Comment by Osanna123** [comment]
TripKey on the Observations level would not be used in the database , but could be used for verification in the submissions.
@Osanna123 and @cmspinto to discuss internally and agree if tripkey is needed in Observations before the next ESAS meeting.

**Comment by Osanna123** [comment]
removed
