### ISSUE TITLE
Question Trip: DistanceBins

### ISSUE THREAD

**Issue by Osanna123** [ices-tools-dev/esas#54]
To better understand the format, I would really like to have this part explained a bit: observation based on the sampling bins, and two related fields in the format: Trip:DistanceBins and Observation:Distance.

**Comment by nicolasvanermen** [comment]
I will try to explain this with an example. 
E.g. during German aerial surveys, observations are aggregated in distance bands of 0-44, 44-91, 91-163 & 163-432, 1000m. In the DistanceBins column in the Trip table, this is noted as 44|91|163|432|1000, which is important input information in any distance anysis. The distance entered in the Observation:Distance column should then equal the middle points of one of those distance bins, i.e. 22, 67.5, 127, 297.5, 716m or in case of observations outside the 1000m boundary, as >1000.

**Comment by peterdesmet** [comment]
@Osanna123 can we close this question? https://ices-tools-dev.github.io/esas/tables/#distancebins
