### ISSUE TITLE
Question Observation: Group

### ISSUE THREAD

**Issue by Osanna123** [ices-tools-dev/esas#55]
To better understand the format, i need a bit more information on the field Group in observations. How is it intended to be used? Which values are expected? Is it a vocab material? Is it placed well in the format?

**Comment by nicolasvanermen** [comment]
This field allows to aggregate multiple observations into one group. This is tradtionally done by means of an incrementing integer per trip. The first group within each trip is coded 1, the second group as 2, and so on.

**Comment by peterdesmet** [comment]
Is now defined at https://ices-tools-dev.github.io/esas/tables/#group

> Identifier of aggregations of individuals of one or several species. Should be unique among all observations from the same `SampleID`.
