### ISSUE TITLE
Avoid word "survey"?

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#57]
@nicolasvanermen should I avoid the word `survey` and rather use `sampling` in the field descriptions?

Examples:
> For typical ship-based **surveys** ... 
> Visual aerial **survey** line transect method with distance sampling
> Visual aerial **survey** strip transect, no distance estimation

**Comment by nicolasvanermen** [comment]
The word can simply be dropped (does not need to be replaced) in case of the SamplingMethod and Ice fields, but I would leave it in in the UseOfBinoculars & Distance fields.
