### ISSUE TITLE
Avoid word "observation bin"?

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#58]
@nicolasvanermen can you clarify "observation bin"? Do we need to include this term and if so, how do I include it in the position description?

**Comment by nicolasvanermen** [comment]
The observation bin is the trajectory sailed between time A & B, between point X & Y. It is (generally) defined by the coordinate of the middle point between point X & Y. All observations done on this trajectory are linked to this position, and was therefore named 'an observation bin'. No inspiration for suitable alternatives though.

**Comment by peterdesmet** [comment]
I have rephrased the position table definition to:

> Positions during sampling. Since the platform moves during sampling, these positions often represent the calculated middle point of a trajectory. These trajectories (called "observation bins") typically have predefined durations (e.g. 2 minutes).

Additional question: is the time then the starttime of the trajectory?

**Comment by nicolasvanermen** [comment]
Perfect! Yes time is expected to be the start time of the trajectory...

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
Ok, I have updated the definition for `time` from:

> UTC time of the observation bin. Format: `hh:mm:ss`.

To:

> Sampling (start) time at the position, in UTC. Format: `hh:mm:ss`.

**Comment by nicolasvanermen** [comment]
Suggestion:
UTC time of the observation bin, defined as the start time of the
trajectory.  Format: hh:mm:ss

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
Ok, can do. Just wanted to avoid the word observation bin.

**Comment by nicolasvanermen** [comment]
This is nonetheless used several times in the positions table?

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
You're right. Updated: https://github.com/ices-tools-dev/esas/commit/65f9c9474ae4784261e5cb36a65f4392154074a4
