### ISSUE TITLE
Use name rather than code for observers

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#6]
Observers (`observer1`, `observer2`, `observer3`) are currently indicated with a fixed code (e.g. `11013` for `Nicolas Vanermen`):

https://github.com/ices-tools-dev/esas/blob/0d294b4ea678e34f52409a16602f9133ac179dcf/_data/table-schemas/trips.yaml#L395-L403

Given that this field is seldom or not used in analysis, can grow in values, and doesn't often share values across data providers, I don't think a code list is a very workable solution here. Especially since it requires data providers to know and consult the list beforehand and that it isn't based on existing codes such as ORCIDs.

I would propose to make the observer fields just regular text fields where the name is indicated and drop the use of a coding table.

Note: additional issues are whether we should have separate observer fields, or just combine those in a single field. And whether the observer should be visible in the (public) data at all considering GDPR.

@nicolasvanermen @ices-tools-dev/data-and-information I would like to have your feedback on this.

**Comment by cmspinto** [comment]
@peterdesmet, what is this information used for?
If this information is not in use then we can just drop  this files and replace it by numberOfObservers (just to know if it was one, two, ...)
 If this information is of use, then we can change to a text field and  need to consider GDPR.
Can you check if it is the full name or just the first name?

**Comment by peterdesmet** [comment]
@nicolasvanermen should be able to answer this, but it looks like I cannot assign him.

**Comment by nicolasvanermen** [comment]
In theory this information can be used in distance analyses, as some
observers are better in detecting birds than others. But to do so is much
more realistic in single monitoring projects than across a large dataset
with so many other and much more important variables to account for
(platform, method,...). Considering this, next to the privacy issues, the
many unknown values, and the doubles inside the list, it might be best to
drop this field...


Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
@nicolasvanermen is this (dropping `observer1,2,3`) something you want to consult Nele, Eric, ... about? I assume observers can still be kept in the source database. Would you add a field `number_of_observers` as @cmspinto suggests or is that of little value?

**Comment by nicolasvanermen** [comment]
Ideally this should be discussed with Nele and the ESAS task group. But in
a way this goes for *all *the reopened issues...

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
Discussed this with @nicolasvanermen and @ericstienen. Decided to drop observer information (name or code) as this information is not used for analyses: especially across datasets. And there are much better fields to use to filter data for analyses. Including observer codes would mean we have to maintain a reference list, including names would complicate making data public (GDPR). So we opted to exclude it altogether.

Done in 7ba6164, closing issue as it does these fields should not be added to the model.
