### ISSUE TITLE
Planing project development

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-dev/esas#61]
**_This is a draft_**
### Sept
- [x] Data Format
- [x] Data Vocabularies
- [x] Database
- [x] Landing Page

### Oct
- [ ] Metadata template and catalogue setup
- [x] User management (Portal)
- [x] Data submission
- [x] Data validation (starting, but will continue into 2022 as things develop)
- [x] Backup

### Nov
- [x] Dataset re-submission
- [x] Submissions overview
- [x] API (long term will develop as stories become more concrete)

### Dec
- [x] Inventory (filter)
- [x] Data download (public)

**Comment by peterdesmet** [comment]
Conclusions of Sep 13 meeting:

- People can submit species data with ESAS or Aphia ID. NT will not be used (#60)
- `ESAS` should be added to RLIST: https://vocab.ices.dk/?ref=44 @Osanna123
- [species.tsv](https://github.com/ices-tools-dev/esas/blob/main/_data/vocabularies/species.tsv) will be used for a database table. EURING mapping information will be retained in that table, even though it won't be used.
- Data downloads should include a link to WoRMS (ID + scientificName) and optionally the "original" scientificName (#63)
- SHIPC codes: codes with an "ok" mapping will be mapped, the rest will be Unknown vessel (#62). @Osanna123 might still create some SHIPC codes for oft-used vessels, but unlikely.
- For the planning, being able to download data is the main target (will be used for EMODNet). Providing documentation to support users in (re)submitting data can come after, as that is unlikely to be started up soon.
- @nicolasvanermen will provide some test files for the next meeting.

**Comment by nicolasvanermen** [comment]
I have an ESAS db version according to the agreed data model fully ready since last week, and subsets can easily be used as test files by the next meeting.

**Comment by peterdesmet** [comment]
Closing this overview issue.
