### ISSUE TITLE
Map historical data to SHIPC

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#62]
1. Always write the shipname in sample `Notes`
2. Ships that could be mapped unambiguously (status: ok) will be submitted with a SHIPC in sample `Platform`
3. Assign 2463 (Tridens I) as: 1987-1990: `64T0` as `Platform` vs 1991-2012: `64T1` as `Platform`
3. All other ships will be mapped with `AA30` (Unknown vessel) as `Platform`

**Comment by nicolasvanermen** [comment]
For me the TRIDENS ships are far from unambiguous. As it has just been decided, two ESAS codes and descriptions are mapped to the same ship (64T2) in case of TRIDENS II & III, while 1 ESAS code will be mapped to two different ships (as for TRIDENS I). Personally, I would map all TRIDENS as unspecified ships...

**Comment by Osanna123** [comment]
@nicolasvanermen As you are the one transferring the data, the final mapping is up to you. But this is not the first dataset to have wrongly mapped data to the multiple ship entries as Tridens. And from the best knowledge we have, we can advice that your ship code 2463 is a multiple hull by the definitions of the Platform Group managing the SHIPC list, and should be split by the data collection date as follows: data 1987-08-10 to 1991-04-14 belong to SHIPC 64T0 and 1991-04-15 to 2012-02-23 belong to 64T1.
Name for your ship code 437 is known to be the unofficial synonyms of the 64T2. I'm not sure how the name for the 421 came to be, but there is no record of the Tridens III, and dates do match with the 64T2.

**Comment by nicolasvanermen** [comment]
We have indeed been mapping Tridens (and other ships that could not be linked to a ShipC code) to ZZ90 in our latest transformations. Likely we can close this issue?

**Comment by Osanna123** [comment]
Yes, sure
