### ISSUE TITLE
Extra taxonomical columns in download

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#63]
Data downloads will include in addition to the originally submitted `SpeciesCodeType` and `SpeciesCode`:

- [x] `SpeciesScientificName`: Scientific name, if available (from ESAS)
- [x] `SpeciesEnglishName`: English name, if available (from ESAS)
- [x] `WormsAphiaID`: Accepted Aphia ID: link to latest accepted name for that taxon in WoRMS
- [x] `WormsScientificName`: Accepted Aphia scientificName: link to latest accepted name for that taxon in WoRMS

Note that "accepted" might be a misnomer, because not all taxa have an accepted name in WoRMS (e.g. Pisces)

**Comment by cmspinto** [comment]
SpeciesScientificName: Scientific name, if available (this will come from the ESAS translation table)
SpeciesEnglishName: English name, if available (this will come from the ESAS translation table)

**Comment by cmspinto** [comment]
Both, in download and WebAPI

![image](https://user-images.githubusercontent.com/8705477/170951784-4371e669-d2a8-478e-aac7-1b2448eb4a35.png)

**Comment by peterdesmet** [comment]
Nice! I notice that empty values are coded as `""` rather than as `null`. I don't think it will cause any issues, but if it is easy to change, I would use `null` values.

```json
"speciesCodeType":"ESAS",
"speciesCode":"5659",
"speciesScientificName":"", <---
"speciesEnglishName":"unidentified wader",
"wormsAphiaID":"2682",
"wormsScientificName":"Charadriiformes"
```

**Comment by cmspinto** [comment]
Yes, it is very easy. 
That came from the value provided in the table, it's null now instead of an empty string:
https://esas.ices.dk/api/getObservationRecords?SpeciesCode=5659
