### ISSUE TITLE
Reinstate custom domain and CNAME

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#64]
The documentation website is currently not working because https://esas-doc.ices.dk cannot be reached. I have [removed](https://github.com/ices-tools-dev/esas/commit/6227e2b5a359841f18b383a20cfb59bff09c7f68) the CNAME file that is causing this, so the site becomes accessible again at https://ices-tools-dev.github.io/esas/

Ideally the CNAME should be reinstated again, but this time:

- Pointing to `esas-docs.ices.dk` (plural docs) or even better `esas.ices.dk/docs/`
- Actually resolve

**Comment by peterdesmet** [comment]
The [site](https://ices-tools-dev.github.io/esas/) is now available again at https://ices-tools-dev.github.io/esas/ (clear your browser cache if you have visited the site before).

**Comment by nicolasvanermen** [comment]
Dag Peter
Ik geraak er desondanks nog steeds niet op (voor de gelegenheid gans mijn
browse geschiedenis gewist). Wil vandaag de csv files goed zetten volgens
het meest recente datamodel, en dan is deze pagina heel handig...
Merci alvast!
Nicolas

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
That is because the CNAME file has been added again by @colinpmillar.

@colinpmillar can you resolve this issue as soon as possible? The site is not available at http://esas-docs.ices.dk/ and we can't see it at https://ices-tools-dev.github.io/esas/ because that one redirects because of the CNAME.

@nicolasvanermen I ran the site locally and made an export for you: [tables page.zip](https://github.com/ices-tools-dev/esas/files/7881633/tables.page.zip). It contains the HTML version of the Tables page, as well as a pdf print.

**Comment by nicolasvanermen** [comment]
Thank you for the follow-up Peter, this should indeed be solved as soon as
possible, we have distributed the original link in several
conferences, hoping for people to join in for future database updates!

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by nicolasvanermen** [comment]
Dag Peter
Heb je zo'n html ook van de species page? Ik word er stilaan kregelig van
dat die redirection nog niet in orde is gebracht, agendapuntje (of
strijdpuntje) voor subiet!
Nicolas

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
This issue has been resolved, website is available at https://esas-docs.ices.dk/
