### ISSUE TITLE
WebAPI

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-dev/esas#65]
WebAPI has available now the option to download the records.

**Comment by cmspinto** [comment]
The following page lists the webservices available at the moment:

https://esas.ices.dk/webservices

For the campaign records we allow the users to download all them, all the other records not authenticated users will only have access to public records.

**Comment by peterdesmet** [comment]
Asked via email, but documenting here as well:

> - Is it possible for the endpoints (campaigns, samples, ...) to have
the same fields as those in the CSV download? E.g. excluding
tblUploadID, ..., adding species information?
> - Is there a specific R package to query these endpoints?

**Comment by cmspinto** [comment]
Yes, this is possible, it will be implemented. 

Carlos

**Comment by cmspinto** [comment]
The fields are the same, the download and the WebAPI use the same classes, but API have the database ID's. These are striped out in the files but we prefer to keep them in the WebAPI.

**Comment by peterdesmet** [comment]
Todo. Note that the descriptions below also fix a number of typos.

- [ ] Add HTML title `Web services`
- [ ] Remove blue alert box
- [ ] Are only the provided parameters available, or are _all_ fields parameters? It is currently odd that e.g. `WindForce` is included.
- [ ] Replace entire intro text with:

> This page lists all web services of European Seabirds At Sea (ESAS). For each API endpoint the description and input parameters are provided, as well as some examples. For less technical access to the data, see the [download page](https://esas.ices.dk/inventory).

## getListSubmissions

- [ ] Why is this not called `getFileSubmissions`?
- [ ] Fix field name typo `submiterEmail` to `submitterEmail`
- [ ] Description:
> Returns file submissions (i.e. how data were submitted to ESAS for each campaign).
- [ ] Example:
> Get all file submissions

## getCampaignRecords

- [ ] Description:
> Returns campaign information.
> Parameters:
> - CampaignID
> - Country
> - DataRightsHolder

- [ ] Examples:
> Get all campaigns
> Get campaigns from Denmark

## getSampleRecords

- [ ] Description:
> Returns sample information. Users authenticated with a JWT token will also have access to restricted data associated with their organization.
> Parameters:
> - CampaignID
> - Country
> - Year
> - PlatformCode
> - TargetTaxa

- [ ] Example:
> Get all public samples
> Get public samples from Denmark
> Get public samples from the year 2014

## getPositionRecords

- [ ] Description
> Returns position information. Users authenticated with a JWT token will also have access to restricted data associated with their organization.
> Parameters:
> - CampaignID
> - Country
> - Year
> - WindForce
> - Visibility

- [ ] Example:
> Get all public positions
> Get public positions from Denmark
> Get public positions from the year 2014

## getObservationRecords

- [ ] Description
> Returns observation information. Users authenticated with a JWT token will also have access to restricted data associated with their organization.
> Parameters:
> - CampaignID
> - Country
> - Year
> - WindForce
> - Visibility

- [ ] Example:
> Get all public observations
> Get public observations from Denmark
> Get public observations from the year 2014

## Token, ScreenESASFile, getScreeningDetails, ...

- [ ] Simplify descriptions
- [ ] Correct typos like `succeds`, `successfuly`

**Comment by cmspinto** [comment]
![image](https://user-images.githubusercontent.com/8705477/168997907-2a7d242a-e187-4b0f-97a2-f8704810d7f3.png)

**Comment by cmspinto** [comment]
@neil-ices-dk or @Osanna123  can you check the description of the last 5 services?

**Comment by neil-ices-dk** [comment]
![image](https://user-images.githubusercontent.com/23527005/169275934-537e2078-83f3-440e-b867-b78fe24b63bd.png)

**Edited text:**
Returns a list of messages from a file screening session, no authentication is needed. 

----

![image](https://user-images.githubusercontent.com/23527005/169276370-448b9f09-5454-41

**Edited text:**
Returns meta information of a screening session, no authentication is needed.

----

![image](https://user-images.githubusercontent.com/23527005/169276761-05c415b2-6d70-45bd-8ed4-0c3daf191b83.png)

**Edited text:**
An authenticated user can push a file (identified by Screening Session ID) to the European Seabirds at Sea database. Requires that the user is the same as the user that generated the Screening Session ID.
The service can be called using post

----
![image](https://user-images.githubusercontent.com/23527005/169277752-3d640db1-ba48-4132-943b-e535e21cd8ac.png)
(why not just ScreenFile?)

**Edited text:**
An authenticated user can upload a file to be screened and validated. 
The service can be called using post and the file will have to be part of the body of the call. 
This service is a pre-requisite to be able to upload data to the database via PushFileToDatabase Service
This file can be later pushed to the database by the same user.

**Comment by neil-ices-dk** [comment]
@cmspinto there is no mention that the file needs to have passed the screening in order to be uploaded via PushtoDatabase; there should be something right?

**Comment by cmspinto** [comment]
Yes, sorry might have missed the obvious!

**Comment by cmspinto** [comment]
![image](https://user-images.githubusercontent.com/8705477/170954989-9566590b-f539-441f-8b43-c77ebcacfdd9.png)

**Comment by neil-ices-dk** [comment]
> ![image](https://user-images.githubusercontent.com/8705477/170954989-9566590b-f539-441f-8b43-c77ebcacfdd9.png)

thanks, could you follow the edited text version in the post further up

**Comment by peterdesmet** [comment]
@cmspinto several things are still missing or wrong:

- [ ] Intro, change to (no space before period):
> see the [download page](https://esas.ices.dk/inventory).

- [ ] Token, change to:
> Returns a JSON Web Token (JWT) that enables the user to make API requests that require authentication.
> A [JWT token](https://jwt.io/introduction).

- [ ] getScreeningSessionMessages, change to:
> Returns a list of messages from a file screening session, no authentication is needed.

- [ ] ScreenESASFile, change to:
> Validates a file that is according to the [European Seabirds At Sea format](http://datsu.ices.dk/web/selRep.aspx?Dataset=148).

- [ ] PushFileToDatabase, change to as suggested by @neil-ices-dk:
> An authenticated user can push a file (identified by Screening Session ID) to the European Seabirds At Sea database.
> Requires that the user is the same as the user that generated the Screening Session ID.
> The service can be called using post.

- [ ] ScreenESASFile: as asked by @neil-ices-dk, why not `ScreenFile`
- [ ] ScreenESASFile, change to as suggested by @neil-ices-dk (currently this text is used for the wrong service):
> An authenticated user can upload a file to be screened and validated.
> The service can be called using post and the file will have to be part of the body of the call.
> This service is a pre-requisite to be able to upload data to the database via PushFileToDatabase Service.

**Comment by cmspinto** [comment]
Done, have I missed something here?
