### ISSUE TITLE
How file association with database should be displayed

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#67]
Discussed on Jan 24 meeting.

A logged in user will see an overview of all uploaded files associated with their organization (even those uploaded by other users of that organization). Per file, the following information is displayed.

- fileName
- uploadDate
- uploadUser
- responsibleOrganization
- country
- count(campaigns)
- min(startDate)
- max(endDate)

Note that the last 3 (dynamic) fields are based on the **associated campaigns in the database**, not what is present in the file. That way, the user can always see what data in the database is associated with a file or (when no data are associated anymore) whether a file is orphaned and can be safely removed.

## Scenario

1. Current overview of files

file | uploaded | by | org | country | campaigns | start | end | actions
--- | --- | --- | --- | --- | --- | --- | --- | ---
[2008_data.txt](#) | 2021-03-01 | nicolas | INBO | BE | 10 | 2008-03-02 | 2008-08-21 | [remove](#)
[2007_data.txt](#) | 2021-03-01 | nicolas | INBO | BE | 10 | 2008-04-01 | 2008-07-18 | [remove](#)

2. I upload a new file with 3 campaigns for 2008 (3 already uploaded ones, 1 new one)
3. System asks if I want to overwrite 3 existing campaigns, I confirm
4. New overview of files:

file | uploaded | by | org | country | campaigns | start | end | actions
--- | --- | --- | --- | --- | --- | --- | --- | ---
[4 campaigns.txt](#) | 2022-01-10 | peter | INBO | BE | 4 | 2008-08-01 | 2008-09-01 | [remove](#)
[2008_data.txt](#) | 2021-03-01 | nicolas | INBO | BE | 7 | 2008-03-02 | 2008-07-25 | [remove](#)
[2007_data.txt](#) | 2021-03-01 | nicolas | INBO | BE | 10 | 2008-04-01 | 2008-07-18 | [remove](#)

**Comment by nicolasvanermen** [comment]
Beautiful!

Nicolas Vanermen
*Wetenschappelijk medewerker*
Instituut voor Natuur- en Bosonderzoek
Havenlaan 88, bus 73, 1000 Brussel
0486/361.582

**Comment by peterdesmet** [comment]
@nicolasvanermen @cmspinto is this overview of uploaded files implemented for logged in users?

**Comment by nicolasvanermen** [comment]
![image](https://user-images.githubusercontent.com/7381853/172840581-57b30a26-e6e4-4cdb-a2bc-13bb39ff9267.png)

**Comment by nicolasvanermen** [comment]
This is the closest I can get, and still quite different from what was proposed by Peter...

**Comment by peterdesmet** [comment]
- [ ] Submission timestamp, not submission date
- [ ] Include number of campaigns contributed to database
- [ ] Include min date contributed to database
- [ ] Include max date contribute to database

**Comment by cmspinto** [comment]
![image](https://user-images.githubusercontent.com/8705477/175504122-cb4c77d6-e9d4-4cef-987c-3997f6c341f7.png)

**Comment by cmspinto** [comment]
Found a way to only give the user that uploaded the file access to the file. 
Have put the validator and the handler in the page. We are not opening any security breach like this.

![image](https://user-images.githubusercontent.com/8705477/175510269-6de76a2c-a81f-496f-b704-e7660228cfe4.png)

**Comment by peterdesmet** [comment]
@cmspinto in the Submissions table, can you:

- First have the column `Data Rights Holder`, then `Country`
- Correct `Campaingns` as `Campaigns`

**Comment by cmspinto** [comment]
Done, thanks for the heads up

**Comment by nicolasvanermen** [comment]
Important to flag here that for the moment, a logged in user can see its own submissions, but as far as I can see, there is no way for a logged in user to check which submissions have been made for the organisation the user is associated to... This will be important for the DRH's that allow me to upload their data. So a seperate page for the latter still needs to be developed...

**Comment by nicolasvanermen** [comment]
Another thing in the view your submissions page, the campaigns column is also referring to the number of campaigns in the database and not in the file of the respective row. This is confusing, and should be more clear based on the column name, or based on a clarifying text above the table, or by listing both the number of campaigns in the file, and the number in the database. So to conclude:

- [ ] develop a new page in which a user can see the files submitted for the institution (s)he is associated with
- [ ] make sure that the information in these table is interpreted correctly (cfr number of campaigns)

**Comment by peterdesmet** [comment]
Let's revisit this issue once the file screening works as expected.

**Comment by cmspinto** [comment]
@peterdesmet  and @nicolasvanermen looking at the code this is already happening!

When a user click in option (c) View list of your database submissions, it shows the all user submissions and the submissions that other user(s) have done to user associated institute.

![image](https://user-images.githubusercontent.com/8705477/188569841-ef52a139-d426-453c-a272-d7602e91a0fe.png)

In this sense it is helpful to have a column with the submitter user name.

![image](https://user-images.githubusercontent.com/8705477/188570615-535155ea-db49-4d10-810f-8f2297038b81.png)

It is possible to do one of two things:
1) Split this page into two pages: "View list of your database submissions" and "View list of  your institute submissions"

2) Rename the link to: "View list of your submissions and your institute submissions"

**Comment by cmspinto** [comment]
> * make sure that the information in these table is interpreted correctly (cfr number of campaigns)

I can change the code to pick the re-submited campaigns that were removed for that file. 

So either the name of the column changes to "Original No. Campaigns" or we split this into two fields, any suggestions?

![image](https://user-images.githubusercontent.com/8705477/188571064-5eee8f24-a539-413a-bf0d-57e9672034c3.png)

**Comment by nicolasvanermen** [comment]
I would prefer two columns: No. of campaigns (database) - No. of campaigns (file)

**Comment by nicolasvanermen** [comment]
> It is possible to do one of two things:
> 
> 1. Split this page into two pages: "View list of your database submissions" and "View list of  your institute submissions"
> 2. Rename the link to: "View list of your submissions and your institute submissions"

Option 1 is the most elegant

**Comment by nicolasvanermen** [comment]
> @peterdesmet and @nicolasvanermen looking at the code this is already happening!
> 
> When a user click in option (c) View list of your database submissions, it shows the all user submissions and the submissions that other user(s) have done to user associated institute.
> 
> ![image](https://user-images.githubusercontent.com/8705477/188569841-ef52a139-d426-453c-a272-d7602e91a0fe.png)
> 
> In this sense it is helpful to have a column with the submitter user name.

Yes, perfect!

**Comment by cmspinto** [comment]
Done, split into two pages:

![image](https://user-images.githubusercontent.com/8705477/188602494-b95639e0-190a-47c3-a5bc-a8d32b62d761.png)

**Comment by cmspinto** [comment]
> No. of campaigns (database)

![image](https://user-images.githubusercontent.com/8705477/188604683-f178f52c-5529-4b28-ad44-baf3534fdc3a.png)


@Osanna123 needs to be tested.

**Comment by nicolasvanermen** [comment]
I can test this only partly, after I start migrating the database. But I am not planning any resubmissions, which makes it hard to test the performance of this table (cfr the number of campaigns in the database versus the number in the file).

**Comment by nicolasvanermen** [comment]
Ideally, one more test is performed after the [milestone test](https://github.com/ices-tools-dev/esas/issues/110). I will supply another datafile, including only 2 JNCC campaigns, when uploading this one, and resubmitting 2 campaigns of the first file then there should be two rows in the submissions overview, one row with 11952/11954 campaigns, and one with 2/2 campaigns. Would that be okay for you Anna?

**Comment by nicolasvanermen** [comment]
The resubmission test went fine! The only remaining issue is flagged [here](https://github.com/ices-tools-dev/esas/issues/125), closing this issue.
