### ISSUE TITLE
Values in PlatformClass

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#71]
Why are Description values in [Platform Class](http://vocab.ices.dk/?ref=311) written as `30: Ship` rather than `Ship`?  As far as I know, none of the other vocabs include the code in the description.

**Comment by nicolasvanermen** [comment]
This is a false remnant, the code should indeed not be included in the
description...

**Comment by Osanna123** [comment]
To my best knowledge, this was a practical implementation for the Code Request Tool for Platforms in 200?, where a displayed description would show both the code and the description. We could fix it this summer, i suppose.
![image](https://user-images.githubusercontent.com/17157764/167793140-de4d0234-c42a-44be-a038-c66b980b3004.png)

**Comment by peterdesmet** [comment]
Thanks, have dealt with it in mapping script. Closing issue.
