### ISSUE TITLE
Inventory of ESAS

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-dev/esas#72]
<html><body>
<p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;" id="docs-internal-guid-50f3ac50-7fff-6f53-820a-0c24f4f5622d"><a href="https://esas.ices.dk/inventory" style="text-decoration:none;"><span style="font-size:11pt;font-family:Arial;color:#1155cc;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">https://esas.ices.dk/inventory</span></a></p><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">On this page you can filter and download European Seabirds at Sea (ESAS) data.</span></p><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Data rights holder / Year / Ecoregion </span><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:#6aa84f;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Apply Criteria</span></p><br /><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:#3c78d8;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Download data</span></p><br /><div dir="ltr" style="margin-left:0pt;" align="left">

Data rights holder | Access | Number of campaigns | First campaign | Last campaign
-- | -- | -- | -- | --
NIOZ | Public | 35 | 2002-03-05 | 2009-12-20
INBO | Public | 55 | 2001-02-01 | 2010-12-22
INBO | Restricted | 10 | 2001-01-15 | 2002-12-01
JNCC | Restricted | 5 | 2008-12-10 | 2009-12-02

</div>
</body>
</html>

Inventory of ESAS should be like described in the document, there are two details:

a) First campaign is the min(startdate), Last Campaign is the max(enddate)

b) DataRight holder is multiple, so the table will group by the combination of them.

Example:

Data rights holder | Access | Number of campaigns | First campaign | Last campaign
-- | -- | -- | -- | --
NIOZ | Public | 35 | 2002-03-05 | 2009-12-20
INBO~NIOZ | Public | 55 | 2001-02-01 | 2010-12-22
INBO~NIOZ | Restricted | 55 | 2003-02-01 | 2014-12-22
INBO | Restricted | 10 | 2001-01-15 | 2002-12-01
JNCC | Restricted | 5 | 2008-12-10 | 2009-12-02

**Comment by cmspinto** [comment]
Looks like this:

![image](https://user-images.githubusercontent.com/8705477/163120293-723fd0e1-d1c9-4a98-adc6-3c4055e9125f.png)

**Comment by nicolasvanermen** [comment]
Looks good... Just wondering wether we could use institute acronyms in the table, it may get bust when writte in full...?

**Comment by cmspinto** [comment]
We only have the description or the code of the institute.

**Comment by peterdesmet** [comment]
@cmspinto can you switch the columns `Access` and `Number of campaigns` in the table, so `Access` is listed first (as originally proposed)?

**Comment by cmspinto** [comment]
![image](https://user-images.githubusercontent.com/8705477/167570041-99a57215-ba75-419f-8430-0d0ce2bd066c.png)

**Comment by peterdesmet** [comment]
Looks good, but is it possible to write the dates as YYYY-MM-DD and without the hour?

**Comment by cmspinto** [comment]
Are we drooping the species filter?

This changes also the download, it's not a quick one!

**Comment by peterdesmet** [comment]
If it is too complicated to drop this filter, it is fine to let it it (after Ecoregion). I just think it will be an unwieldy long list.

**Comment by cmspinto** [comment]
The work is to create the new ones not to drop the species!

Do we need these ones: Data rights holder / Access?

**Comment by peterdesmet** [comment]
Yes, Data Rightsholder and Access are useful ones to have.

**Comment by cmspinto** [comment]
Was able to keep it in one line 👍 
![image](https://user-images.githubusercontent.com/8705477/169470021-6d9515c5-2bdd-42e3-ace0-1ea4d2323880.png)
