### ISSUE TITLE
Download request page

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-dev/esas#73]

**Comment by cmspinto** [comment]
Done, please test it.

**Comment by peterdesmet** [comment]
Nice. Some more issues that popped up:

- [ ] Minor: please close the sentence with a period after accessions@ices.dk
- [ ] I tried the email form, but it resulted in an error

> An error occurred while processing your request. Development Mode. Swapping to the Development environment displays detailed information about the error that occurred. The Development environment shouldn't be enabled for deployed applications. It can result in displaying sensitive information from exceptions to end users. For local debugging, enable the Development environment by setting the ASPNETCORE_ENVIRONMENT environment variable to Development and restarting the app.

Two more general layout questions:

- [ ] Why is it that no normal HTML markup is used (e.g. `<p>` for paragraphs, `<h2>` for titles)?
- [ ] Is it possible to use regular Bootstrap form layout (https://getbootstrap.com/docs/4.6/components/forms/) for the email form. It currently looks unaligned and not great on small screens.

**Comment by cmspinto** [comment]
I tried the email form, but it resulted in an error, 

this is the part that will be developed, it's not finished yet. This will need to incorporate the logic of permissions.

**Comment by cmspinto** [comment]
Working now :

![image](https://user-images.githubusercontent.com/8705477/169530162-3a950176-ae54-4d6b-991d-c73887e9284d.png)


Nicolas did you received the email?

**Comment by nicolasvanermen** [comment]
Yes!!
