### ISSUE TITLE
Test if integer values for ObservationDistance can be used

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#76]
@nicolasvanermen have you tested if integer values can be used for `ObservationDistance`? The term should accept controlled values (A, B, C) as well as integer values.

**Comment by peterdesmet** [comment]
The same applies to `TravelDirection` which can have a mix of cardinal directions and degrees.

**Comment by peterdesmet** [comment]
It has no vocabulary attached, even though it has one (https://vocab.ices.dk/?ref=1714)?

**Comment by nicolasvanermen** [comment]
Tested by uploading distances A & 100 and travel directions N & 90, and all passed the screening.

**Comment by peterdesmet** [comment]
What campaign ID?

**Comment by nicolasvanermen** [comment]
110000153, and then generated fictive data:
OBSERVATIONS$TravelDirection <- rep(c("N",90),188)
OBSERVATIONS$ObservationDistance <- rep(c("A",100),188)

**Comment by nicolasvanermen** [comment]
[ESAS_BE_DATA_test_obis_tab.csv](https://github.com/ices-tools-dev/esas/files/8861768/ESAS_BE_DATA_test_obis_tab.csv)
[ESAS_BE_DATA_test_comma_etcetera.csv](https://github.com/ices-tools-dev/esas/files/8861769/ESAS_BE_DATA_test_comma_etcetera.csv)
[ESAS_BE_DATA_test_ERID.csv](https://github.com/ices-tools-dev/esas/files/8861770/ESAS_BE_DATA_test_ERID.csv)

**Comment by nicolasvanermen** [comment]
I uploaded these 3 files to the database, with respective campaignID's of 110000153, 110000154 & 110000155. As mentioned, currently, I cannot check the submissions, neither can I perform any data download.

**Comment by peterdesmet** [comment]
Thanks for the identifiers, it seems like those data are currently not making it to the database.
- 110000153 is there with old data: https://esas.ices.dk/api/getObservationRecords?campaignID=110000153
- 110000154 not included: https://esas.ices.dk/api/getObservationRecords?campaignID=110000154
- 110000155 not included: https://esas.ices.dk/api/getObservationRecords?campaignID=110000155

**Comment by peterdesmet** [comment]
@cmspinto is it possible to investigate why campaignID 110000153, 110000154 & 110000155 are not accessible in the API? 

@nicolasvanermen are these set to restricted access?

**Comment by nicolasvanermen** [comment]
No public access

**Comment by peterdesmet** [comment]
Any indication in your submission page whether these are uploaded?

**Comment by nicolasvanermen** [comment]
No they are not inside the submission page. I can do this again if you want, but I have the feeling we are running in circles here.

**Comment by nicolasvanermen** [comment]
See issue 88, they should be in the database now.

**Comment by peterdesmet** [comment]
I still have:

- 110000153 is there with old data: https://esas.ices.dk/api/getObservationRecords?campaignID=110000153
- 110000154 not included: https://esas.ices.dk/api/getObservationRecords?campaignID=110000154
- 110000155 not included: https://esas.ices.dk/api/getObservationRecords?campaignID=110000155

Or am I looking at the wrong campaigns?

**Comment by nicolasvanermen** [comment]
So: yet these files are in my download, but are not accessible through the API?

**Comment by peterdesmet** [comment]
Not entirely:

- [campaign API](https://esas.ices.dk/api/getCampaignRecords?campaignID=110000155): record can be found
- [sample API](https://esas.ices.dk/api/getSampleRecords?campaignID=110000155): broken API
- [position API](https://esas.ices.dk/api/getPositionRecords?campaignID=110000155): records can be found
- [observation API](https://esas.ices.dk/api/getObservationRecords?campaignID=110000155): **empty result set**

**Comment by cmspinto** [comment]
> * 110000154

Nop, all good.

**Comment by peterdesmet** [comment]
👍 Did you change something? Because it was empty before.

**Comment by peterdesmet** [comment]
To get back to the original purpose of this issue:

https://esas.ices.dk/api/getObservationRecords?observationID=1100032322

```
"observationDistance": "100",
"travelDirection": "90"
```

**Test passed** Integer values do make it correctly into the database and the API. They are returned as strings, but that is expected, since both fields also accept letters (see https://esas.ices.dk/api/getObservationRecords?observationID=1100032323).

**Comment by cmspinto** [comment]
I have put now @nicolasvanermen  with rights for organization 200, so you should be able to re-upload files.

Question is, if a user upload the file, should the user be able to overwrite that file event do he does not have the right permissions for that organization?

**Comment by peterdesmet** [comment]
@cmspinto I created a separate issue for your question at https://github.com/ices-tools-dev/esas/issues/91, so that this issue can remain closed.

**Comment by nicolasvanermen** [comment]
All test files have organisation 202, INBO
