### ISSUE TITLE
UseOfBinoculars contains incorrect values in download

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#77]
Data that were uploaded with `Sample.UseOfBinoculars = 1` have `Sample.UseOfBinoculars = FO` in the download. Where is this value coming from? Normally the only allowed values are 1, 2, 3: https://vocab.ices.dk/services/rdf/collection/UseOfBinoculars

**Comment by cmspinto** [comment]
This one was a good catch, thanks. Corrected now in the import procedure, it was importing the code instead of the ID.

![image](https://user-images.githubusercontent.com/8705477/165478920-e9ee4a25-22e5-48a6-8d69-bbfd4dc102e4.png)

**Comment by neil-ices-dk** [comment]
@Osanna123 to test and confirm

**Comment by Osanna123** [comment]
output from 23/09/22 works ok
