### ISSUE TITLE
Distance values are expressed as integers in export

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#78]
`Position.Distance` values that were uploaded as doubles are expressed as integers in the Download: `0.7 -> 0`. This should be fixed.

**Comment by cmspinto** [comment]
Good catch, for some reason it was integer instead of float, 

corrected now:

![image](https://user-images.githubusercontent.com/8705477/165479577-1a01c407-4f0d-4927-b021-248ae9b982cc.png)
