### ISSUE TITLE
Visibility values are NULL in Download

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#79]
`Position.Visibility` values (not NULL) are empty in Download. This should be fixed.

**Comment by cmspinto** [comment]
Hi Peter, another excellent catch. 
It's great to work like this.
It was not picking the visibility codes from the current file, so the codes were not being imported to the database.

Very easy to correct but not so easy to catch, great job.
Thanks.

**Comment by neil-ices-dk** [comment]
@Osanna123 to test
