### ISSUE TITLE
Disclaimer for ESAS

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-dev/esas#80]
We need a disclaimer proposal for ESAS.

The current one was adapted from another dataset.

**Comment by peterdesmet** [comment]
A disclaimer text was proposed in the Google doc. Should I copy it here?

**Comment by cmspinto** [comment]
We should put the file here and I will copy that to the website.

**Comment by nicolasvanermen** [comment]
Here is the link with the review of the ESAS website pages:
https://docs.google.com/document/d/1JaDbchwtM5Z9E84ICkxpZKEJCv7mGes9lJMgXXx_Wpg/edit#heading=h.lnwz9o48dby9


Nicolas Vanermen
Instituut voor Natuur- en Bosonderzoek
(Research Institute for Nature and Forest)
Havenlaan 88, bus 73, 1000 Brussel
+32 486 361 582

**Comment by peterdesmet** [comment]
This is the text for the disclaimer:

---

**Please acknowledge the following conditions before downloading data:**

- All public data are licensed under the Creative Commons (CC BY 4.0) license.
- You have sole responsibility for correct and appropriate data interpretation.
- Results, conclusions, and/or recommendations derived from the data do not imply endorsement from ICES.
- You are requested to inform ICES of any suspected problems in the data.
- Derived data products are based on public and restricted data.

The full ICES data policy and terms of use can be viewed [here](https://ices.dk/data/guidelines-and-policy/Pages/ICES-data-policy.aspx).

**Restricted Data**

Some data in the European Seabirds At Sea (ESAS) are classified as restricted by the data rights holder(s) and licensed under the [ICES Biodiversity License](https://www.ices.dk/sites/pub/Publication%20Reports/Guidelines%20and%20Policies/ICES-Data-Licence-Biodiversity.pdf). You can request full access to those data at the discretion of the data rights holder(s).

---

**Comment by peterdesmet** [comment]
Note sure we have to mention the "Derived data products are based on public and restricted data.", since there aren't any derived data products yet.

**Comment by neil-ices-dk** [comment]
standard disclaimer revised for ESAS https://github.com/ices-tools-dev/esas/blob/main/disclaimer-download

**Comment by cmspinto** [comment]
Done, have we agree to list all the data custodians or to put a reference to ESAS dateset?

**Comment by peterdesmet** [comment]
I think the idea was to list the data providers:

1. In the ESAS metadata (in a reference system)
2. (Potentially) the ESAS homepage
3. The included ones in the disclaimer file

I assume this issue is mostly about the disclaimer file, but not that the disclaimer popup is not centered:

![European-Seabirds-at-Sea-](https://user-images.githubusercontent.com/600993/169029168-2f990e8f-d663-4849-b202-b64e108cfc8b.png)

**Comment by neil-ices-dk** [comment]
> Done, have we agree to list all the data custodians or to put a reference to ESAS dataset?

as Peter says, the main reference would be the Full Metadata Record;

**Comment by cmspinto** [comment]
Create a metadata record for the ESAS dataset.

ICES will create a first draft of the metadata record and Nicolas or Peter can review the metadata record.

**Comment by nicolasvanermen** [comment]
ICES European Seabirds at Sea (ESAS) Database ->  ICES European Seabirds **A**t Sea (ESAS) **d**atabase

**Comment by neil-ices-dk** [comment]
the disclaimer is 99% ready, just missing the link to the metadata URL for the dataset

**Comment by neil-ices-dk** [comment]
@cmspinto the URL is now included in https://github.com/ices-tools-dev/esas/blob/main/disclaimer-download

@peterdesmet the metadata record for reference:
http://gis.ices.dk/geonetwork/srv/eng/catalog.search#/metadata/7a6151e4-812b-4455-97a2-74c5102d418f

**Comment by peterdesmet** [comment]
@neil-ices-dk Metadata record looks good! The spatial extend can be bigger (especially south). I think the total bounding box is:

80N,-40E -> 10N,30E

![esas-records](https://user-images.githubusercontent.com/600993/173764345-eb8f0b79-c280-4a4a-9558-4a904538eeec.png)

**Comment by neil-ices-dk** [comment]
thanks @peterdesmet updated as below:
![image](https://user-images.githubusercontent.com/23527005/173779544-05d87935-0ff1-4ef6-a219-4e1f73c39826.png)

**Comment by neil-ices-dk** [comment]
> This looks nice indeed. Will we include a list of the data providers there?

good point, i forgot that - will look into how best to put them in

**Comment by nicolasvanermen** [comment]
![image](https://user-images.githubusercontent.com/7381853/174076904-babb0603-93cd-4a78-a097-b5a00d16bc43.png)

- [ ] ICES European Seabirds at Sea (ESAS) Database -> ICES European Seabirds At Sea (ESAS) database
- [ ] Hyperlink instead of full webadress
- [ ] Adjust font size of text under Restricted Data

**Comment by cmspinto** [comment]
> [x] ICES European Seabirds at Sea (ESAS) Database -> ICES European Seabirds **A**t Sea (ESAS) **d**atabase

@Osanna123 can you also change it in DATSU adn Reco?

**Comment by nicolasvanermen** [comment]
- [ ] Database -> database
