### ISSUE TITLE
Web API returns primarySampling + transect as text, not boolean

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#81]
The https://esas.ices.dk/api/getSampleRecords API returns `primarySampling` as a long text (with lots of spaces), rather than a boolean:

```
"primarySampling": "TRUE                                                        ",
```

Please change to:

```
"primarySampling": true,
```

It would also be good if https://esas.ices.dk/api/getObservationRecords returned:

```
"transect": true,
```

Rather than the current text value `"TRUE"`

**Comment by nicolasvanermen** [comment]
Likely this needs to be:
 "primarySampling": true,
?

And why are all the column names written as "primarySampling" and not as the original "PrimarySampling", or "transectWidth" instead of "TransectWidth"?

**Comment by peterdesmet** [comment]
Indeed, I was also wondering why it changed from UpperCamelCase to lowerCamelCase.

**Comment by cmspinto** [comment]
It's a boolean now:

![image](https://user-images.githubusercontent.com/8705477/170946024-bd69585b-d2de-42b1-a7a5-0e5cdaad3d87.png)


![image](https://user-images.githubusercontent.com/8705477/170945925-f5300ffd-33d9-4e28-9f55-45299ed9006c.png)

**Comment by cmspinto** [comment]
Have checked it and here it is provided as a boolean: https://esas.ices.dk/api/getSampleRecords

![image](https://user-images.githubusercontent.com/8705477/172352852-2f776474-1e8b-491a-9a00-01b63d9aad29.png)

@peterdesmet could you provide an URL?

**Comment by peterdesmet** [comment]
`primarySampling` is indeed correct, but `transect` is not. I added that field later to this issue, so you might have missed it.

**Comment by cmspinto** [comment]
Transect is a bool: 
![image](https://user-images.githubusercontent.com/8705477/174785142-048bb4d7-bb1e-499d-b8e2-0d037ced182e.png)


[https://esas.ices.dk/api/getObservationRecords?latitude=59.7,53.2](https://esas.ices.dk/api/getObservationRecords?latitude=59.7,53.2)


![image](https://user-images.githubusercontent.com/8705477/174785310-41fd2e00-5037-4891-a794-aaf09bd414ad.png)


Can we close this one.
