### ISSUE TITLE
Add parameter `dataAccess` to getCampaignRecords

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#82]
It would be useful to have the parameter `dataAccess` in https://esas.ices.dk/api/getCampaignRecords, so one can query:

https://esas.ices.dk/api/getCampaignRecords?dataAccess=Public

**Comment by cmspinto** [comment]
Done,

[https://esas.ices.dk/api/getCampaignRecords](https://esas.ices.dk/api/getCampaignRecords)

![image](https://user-images.githubusercontent.com/8705477/170940738-96f02fef-2058-4742-ab5e-703162331fb4.png)

**Comment by cmspinto** [comment]
Yes, now it can: [https://esas.ices.dk/api/getCampaignRecords?dataAccess=Public](https://esas.ices.dk/api/getCampaignRecords?dataAccess=Public)

It was not one of the filters but it's a good idea to add this filter.
