### ISSUE TITLE
Align File_Information / Campaigns documentation with API, CSV + remove dataCustodian fields

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#86]
## Data custodian fields

See comment at https://github.com/ices-tools-dev/esas/issues/74#issue-1208115854, the fields `dataCustodian` and `dataCustodianContact` no longer serve a purpose and should be removed from:

- [x] File format
- [x] Documentation site @peterdesmet
- [x] CSV
- [x] API

In addition, there are so fields to be added/removed to make format, CSV and API align:

## File_Information

Field | [Format](http://datsu.ices.dk/web/selRep.aspx?Dataset=148) | CSV | [API](https://esas.ices.dk/api/getFileSubmissions)
--- | ---  | --- | ---
tblUploadID | - | - | ok, added by system
insDateTime | - | - | ok, added by system
accessionID | - | - | ok, added by system
fileName | - | - | ok, added by system
user | - | - | ok, added by system
submitterEmail | - | - | ok, added by system
institution | - | - | ok, added by system
RecordType | ok | - | -
DataRightsHolder | ok | - | add!
Country | ok | - | ok 
DataCustodian* | remove! | - | -
DataCustodianContact* | remove! | - | -
campaignID | - | - | ~keep, is a link to campaignID~ remove
dataAccess | - | - | remove!

## Campaigns

Field | [Format](http://datsu.ices.dk/web/selRep.aspx?Dataset=148) | CSV | [API](https://esas.ices.dk/api/getCampaignRecords)
--- | --- | --- | ---
tblUploadID | - | - | ok
tblCampaignID | - | - | ok
dataRightsHolder | - | ok, moved down from file info | ok, moved down from file info
country | - | ok, moved down from file info | ok, moved down from file info
submiterEmail | - | - | remove! (also typo)
submiterUserName | - | - | remove! (also typo)
accessionID | - | - | remove!
insDateTime | - | - | remove!
dataCustodian | - | remove! | remove! (appears at end)
dataCustodianContact | - | remove! | remove! (appears at end)
RecordType | ok | - | -
CampaignID | ok | ok | ok
DataAccess | ok | ok | ok
StartDate | ok | ok | ok
EndDate | ok | ok | ok
Notes | ok | ok | ok

**Comment by cmspinto** [comment]
Need a bit more information about this, but if I'm understanding correctly, in the data format, [File_Information](datsu.ices.dk/web/selRep.aspx?Dataset=148), the DataCustodian and DataCustodianContact  should be removed?
Is it because we are not using this information?

**Comment by peterdesmet** [comment]
That is correct.

**Comment by cmspinto** [comment]
Have removed the dataRightsHolder and the country from the campaign record.

I think the rest is now align.

**Comment by peterdesmet** [comment]
> Have removed the dataRightsHolder and the country from the campaign record.

@cmspinto but that was not what was described above. Other things have been fixed though. Here are the remaining issues:

- [ ] https://esas.ices.dk/api/getCampaignRecords, add `DataRightsHolder` and `Country` again, between `tblCampaignID` and `CampaignID`:

```
tblUploadID
tblCampaignID
DataRightsHolder
Country
CampaignID
DataAccess
StartDate
EndDate
Notes
```

- [ ] https://esas.ices.dk/api/getFileSubmissions API: `submitterEmail`, `institution` fields were removed. I think that is fine considering GDPR
- [ ] https://esas.ices.dk/api/getFileSubmissions API: `campaignID` was removed. I guess the relationship between a campaign record and the fileSubmission can be traced back using `campaign. tblUploadID`?
- [ ] https://esas.ices.dk/api/getFileSubmissions API: order the last 3 elements as: `user`, `dataRightsHolder`, `country`
