### ISSUE TITLE
Submission page

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-tools-dev/esas#87]
https://esas.ices.dk/manage/menu
@cmspinto 
- [x] currently c) [View your database submissions] is not active
- [x] Neither could I check the resubmission page...
- [x] The excell template is outdated: update or delete link?

**Comment by nicolasvanermen** [comment]
![image](https://user-images.githubusercontent.com/7381853/172385693-f7c07e0c-ba19-4880-8347-e84460b2c7f0.png)

**Comment by nicolasvanermen** [comment]
please see the [google doc](https://docs.google.com/document/d/1JaDbchwtM5Z9E84ICkxpZKEJCv7mGes9lJMgXXx_Wpg/edit?usp=sharing) with suggestions for revising the (re)submission pages

**Comment by cmspinto** [comment]
Submissions page for the user done, user can see and delete the submissions that the user uploade or the ones where the user is responsible for the Data Rights Holder: 

![image](https://user-images.githubusercontent.com/8705477/172571707-5ff23822-f391-4c96-b0c0-593e8d4553f8.png)

**Comment by nicolasvanermen** [comment]
Looks good, but somehow I cannot access this page.

**Comment by cmspinto** [comment]
Hi Nicolas, it was not published yet!

The rules are, a user can delete the files that:
a) the user uploaded 
b) files where at least one of data rights holder is manage by the user.

**Comment by nicolasvanermen** [comment]
OK, now I can reach it:

- [ ] Subiter -> Submitter
- [ ] Ins. Date Time: what does this stand for? I propose: Submission Date (note that time is not indicated)
- [ ] when deleting a file the page jumps back to the main menu, while it seem logical that you simply stay on the same page

**Comment by cmspinto** [comment]
Have we tackle this:

![image](https://user-images.githubusercontent.com/8705477/172841705-d0869c7d-3353-4be1-be1e-e298c13c21bb.png)

**Comment by nicolasvanermen** [comment]
No the proposed changes were not yet implemented...!

**Comment by cmspinto** [comment]
> No the proposed changes were not yet implemented...!

A bit lost, could you help me to locate the changes to be done?

**Comment by nicolasvanermen** [comment]
The proposed changes are in the [google doc](https://docs.google.com/document/d/1JaDbchwtM5Z9E84ICkxpZKEJCv7mGes9lJMgXXx_Wpg/edit);

**Comment by cmspinto** [comment]
![image](https://user-images.githubusercontent.com/8705477/175018940-e3e35a44-5973-4604-9ebf-d00bdf3f70e1.png)

Is there any typo?
