### ISSUE TITLE
Upload file with WoRMS code

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#88]
@nicolasvanermen can you test uploading a file where rather than the ESAS code, the AphiaID is provided?

So an observation record with:

- SpeciesCodeType: ERID
- SpeciesCode: 1457401 (this is Vulpes vulpes)

The intent is that this is possible, so users can submit species that are not on the [ESAS list](https://esas-docs.ices.dk/species/) but that are on WoRMS, but I don't think this was tested.

- [x] Does not through QA error
- [x] Should be returned by API as:

```
speciesCodeType: ERID
speciesCode: 1457401
speciesScientificName: Vulpes vulpes (?)
speciesEnglishName: empty
wormsAphiaID: 1457401
wormsScientificName: Vulpes vulpes
```

> Regarding the resubmission, I thought I will check this again yet the earlier accepted [ESAS_BE_DATA_test_obis_tab.csv](https://github.com/ices-tools-dev/esas/files/8861768/ESAS_BE_DATA_test_obis_tab.csv) gives an error when screening, while before it did not, how come?

Hi Nicolas, 
This is not a valid file:
![image](https://user-images.githubusercontent.com/8705477/174261814-786ca0ee-4ac0-43b6-b4da-5da032ddcd85.png)

You are considering that the whole line is a string: "FI	202	BE	202	info@inbo.be"

**Comment by nicolasvanermen** [comment]
Uploaded a file with ERID instead of ESAS codes. It did not return errors, so this seems to be fine. Failed to check the download though as the download button returns a blank page.  @cmspinto how come?

**Comment by nicolasvanermen** [comment]
Imported again, two of them indeed came through, the resubmission did not it seems? (still the upload of 27/04, although I opted to overwrite).

**Comment by nicolasvanermen** [comment]
![image](https://user-images.githubusercontent.com/7381853/174088078-0a3c5248-ad34-46b1-a95c-22d95172f7e5.png)

**Comment by nicolasvanermen** [comment]
And why are these campaigns split in two rows?

**Comment by cmspinto** [comment]
Download and inventory are fixed now :).

Thanks for the heads up:

![image](https://user-images.githubusercontent.com/8705477/174246473-a569b6bf-c36f-43a6-8fae-f6f73a01a872.png)

**Comment by nicolasvanermen** [comment]
![image](https://user-images.githubusercontent.com/7381853/174247435-b164f8fb-14e9-4b04-abb3-2fd607746897.png)

**Comment by nicolasvanermen** [comment]
In the download page the campaigns are still split into two row, while they should be aggregated in one.

**Comment by cmspinto** [comment]
Correct, it was not grouping correctly.

**Comment by nicolasvanermen** [comment]
Now I see the 110000155 campaing is no longer in our submissions...? I redirected Peter to this issue, because he wanted to perform some testing on these 3 campaigns...

**Comment by nicolasvanermen** [comment]
So now there are 2 campaigns in the submission, but three in the download... I don't get this...

**Comment by nicolasvanermen** [comment]
Regarding the resubmission, I thought I will check this again yet the earlier accepted [ESAS_BE_DATA_test_obis_tab.csv](https://github.com/ices-tools-dev/esas/files/8861768/ESAS_BE_DATA_test_obis_tab.csv) gives an error when screening, while before it did not, how come?

**Comment by peterdesmet** [comment]
😕 this is frustrating. @cmspinto can you check? From the issues here, the (re)submission seems buggy right now.

**Comment by peterdesmet** [comment]
@cmspinto I don't understand your comment. I mainly want to check records @nicolasvanermen has uploaded, but can't access them via the API, see https://github.com/ices-tools-dev/esas/issues/76#issuecomment-1158627756

**Comment by cmspinto** [comment]
Had to re-upload the files.

**Comment by peterdesmet** [comment]
**Test passed**, records uploaded with ERID rather than ESAS `speciesCodeType` are correctly presented by the API: https://esas.ices.dk/api/getObservationRecords?campaignID=110000155

```json
"speciesCodeType": "ERID",
"speciesCode": "137188",
"speciesScientificName": "Gavia stellata",
"speciesEnglishName": "red-throated diver",
"wormsAphiaID": "137188",
"wormsScientificName": "Gavia stellata",
```

vs e.g [record with ESAS](https://esas.ices.dk/api/getObservationRecords?observationID=1100032238):

```json
"speciesCodeType": "ESAS",
"speciesCode": "59",
"speciesScientificName": "Gavia sp.",
"speciesEnglishName": "unidentified diver",
"wormsAphiaID": "137057",
"wormsScientificName": "Gavia",
```

**Comment by peterdesmet** [comment]
@nicolasvanermen can this issue be closed? E.g. is https://github.com/ices-tools-dev/esas/issues/88#issuecomment-1158576082 resolved?

**Comment by nicolasvanermen** [comment]
This comment seems to be resolved... Campaigns aggregated in one line. 
Yet when performing the download the observations are not linked to the right observation ID's that were in the three entry files. All data seem to be mingled... @cmspinto please: how is this possible?

**Comment by nicolasvanermen** [comment]
We figured this out: the appartent mingling was due to an old file (ESAS_BE_DATA_test_obis_tab_ERID.csv) that was in the database, instead of the most recent upload (ESAS_BE_DATA_test_obis_tab.cs), both with the same campaignID; very glad this was figured out, and that there is a logical explanation... Still very confusing because in the overview of file screenings it seems to suggest that the latter file (88) was uploaded to the database, hereby overwriting the former file (86):
![image](https://user-images.githubusercontent.com/7381853/174751958-67bfa859-807d-4759-a184-81f295cb91f5.png)

**Comment by nicolasvanermen** [comment]
So concluding: it remains to be tested whether the status "File already uploaded to the database" actually holds true.

**Comment by peterdesmet** [comment]
A separate issue has been created for testing file overwrites. This issue can be closed.
