### ISSUE TITLE
Define parameters for API endpoints

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#89]
## getFileSubmissions

- [x] DataRightsHolder: https://esas.ices.dk/api/getFileSubmissions?dataRightsHolder=630
- [x] Country: https://esas.ices.dk/api/getFileSubmissions?country=BE
- [x] ~CampaignID~

## getCampaignRecords

- [x] DataRightsHolder (not ResponsibleOrganization): https://esas.ices.dk/api/getCampaignRecords?DataRightsHolder=630
- [x] Country: https://esas.ices.dk/api/getCampaignRecords?Country=NL
- [x] CampaignID: https://esas.ices.dk/api/getCampaignRecords?CampaignID=110000156
- [x] DataAccess: https://esas.ices.dk/api/getCampaignRecords?dataAccess=Public
- [x] Year, as a range query: `year=2012,2014`, filters on `StartDate`.
  - [x] https://esas.ices.dk/api/getCampaignRecords?year=1996
  - [x] https://esas.ices.dk/api/getCampaignRecords?year=2020,2021

## getSampleRecords

- [x] CampaignID: https://esas.ices.dk/api/getSampleRecords?CampaignID=110000153
- [x] SampleID: https://esas.ices.dk/api/getSampleRecords?SampleID=110000153
- [x] Year, as a range query: `year=2012,2014`, filters on `Date`
  - [x] https://esas.ices.dk/api/getSampleRecords?year=1996
  - [x] https://esas.ices.dk/api/getSampleRecords?year=2020,2021
- [x] PlatformCode: https://esas.ices.dk/api/getSampleRecords?PlatformCode=11BE
- [x] PlatformClass: https://esas.ices.dk/api/getSampleRecords?platformClass=30
- [x] PrimarySampling, as boolean: `primarySampling=true`: https://esas.ices.dk/api/getSampleRecords?PrimarySampling=false
- [x] ~Country~: remove
- [x] ~TargetTaxa~: remove

## getPositionRecords

- [x] CampaignID: https://esas.ices.dk/api/getPositionRecords?campaignID=110000155
- [x] SampleID: https://esas.ices.dk/api/getPositionRecords?sampleID=110000155
- [x] PositionID: https://esas.ices.dk/api/getPositionRecords?positionID=110004762
- [x] Latitude, as a range query: `latitude=51,53`: https://esas.ices.dk/api/getPositionRecords?latitude=51.1,51.2
- [x] Longitude, as a range query: `longitude=51,53`: https://esas.ices.dk/api/getPositionRecords?longitude=2.5,2.6
- [x] ~Country~: remove
- [x] ~WindForce~: remove
- [x] ~Visibility~: remove
- [x] ~Year~: remove

## getObservationRecords

- [x] CampaignID: https://esas.ices.dk/api/getObservationRecords?campaignID=110000155
- [x] SampleID: https://esas.ices.dk/api/getObservationRecords?sampleID=110000155
- [x] PositionID: https://esas.ices.dk/api/getObservationRecords?positionID=110004762
- [x] ObservationID: https://esas.ices.dk/api/getObservationRecords?observationID=1100032257
- [x] SpeciesCode: https://esas.ices.dk/api/getObservationRecords?speciesCode=2130
- [x] WormsAphiaID: https://esas.ices.dk/api/getObservationRecords?wormsAphiaID=137073
- [x] ~Country~: remove
- [x] ~LifeStage~: remove
- [x] ~Sex~: remove

**Comment by peterdesmet** [comment]
@cmspinto see above the list of parameters that I think make sense for each endpoint, to be listed in the documentation in that order.

**Comment by cmspinto** [comment]
I think it makes sense to allow multiple values per parameter, but not the year as a range. 
I think that if the user wants to filter for 2014-2017 then it can specify 2014,2015,2016,2017
Allowing multiple values also allows the range, but not the other way around!

**Comment by peterdesmet** [comment]
Would work too. My suggestion was inspired by how GBIF implements range queries (see https://www.gbif.org/developer/summary#common). For long ranges, that is more user friendly than listing all the years.

**Comment by cmspinto** [comment]
Same comment to Latitude and Longitude:

**Comment by peterdesmet** [comment]
I find that a counter intuitive way of working, because latitude/longitudes are not integers, so how do you define the range `51.5 -> 51.7`? Fairly easy to do when you only have two parameters (min/max): `latitude=51.5,51.7`, but harder if you have to specify every element in the range. Imo, the multiple comma approach you suggest seems also harder to implement.

**Comment by cmspinto** [comment]
ok, have put latitude as a range, give here an example in the page: [https://esas.ices.dk/webservices](https://esas.ices.dk/webservices).

![image](https://user-images.githubusercontent.com/8705477/174019491-ad09b969-e712-4290-a678-5902e8d1ac54.png)

**Comment by peterdesmet** [comment]
@cmspinto see the issues described in my comment above: not everything works as it should.

**Comment by cmspinto** [comment]
This was changed for the latitute to be a range: [https://esas.ices.dk/api/getPositionRecords?latitude=49.7,53.2](https://esas.ices.dk/api/getPositionRecords?latitude=49.7,53.2)

**Comment by cmspinto** [comment]
_? I also notice the links on that page in two colours of blue ?_
Is this because of the non visited links and the visited links? 
That is the default.

**Comment by cmspinto** [comment]
Don't understand this comment:
@peterdesmet  _https://esas.ices.dk/api/getCampaignRecords?Year=2021 returns too many results (ok for other endpoints)_

**Comment by peterdesmet** [comment]
I am getting `startDate`s in 2020 if I do https://esas.ices.dk/api/getCampaignRecords?Year=2021. For the other endpoints that have the year parameter, I don't encounter this issue.

The typo has not been fixed yet, so I unchecked that box again.
https://esas.ices.dk/api/getSampleRecords is broken

**Comment by cmspinto** [comment]
> I am getting `startDate`s in 2020 if I do https://esas.ices.dk/api/getCampaignRecords?Year=2021. For the other endpoints that have the year parameter, I don't encounter this issue.
> 
> The typo has not been fixed yet, so I unchecked that box again. https://esas.ices.dk/api/getSampleRecords is broken

It was using the data of the samples instead of the campaign startdate. Changed it but we can talk about this in the meeting.

**Comment by cmspinto** [comment]
We should be able to close this one.

**Comment by peterdesmet** [comment]
I would say:

- For `getCampaignRecords`, use the campaign.`startDate` as the basis for `year`
- For `getSampleRecords`, use the sample.`date`  as the basis for `year`

You could also use `startDate` for both, as it is unlikely that campaigns will cross years.

**Comment by peterdesmet** [comment]
> We should be able to close this one.

No:

- [ ] Typo not fixed (still says `Get public positions from latitutes 49.7 to 53.2`) Change to `Get public positions from latitudes 49.7 to 53.2`
- [ ] Remove listed `CampaignID` parameter from getFileSubmissions, as it is _not_ returned by the API. It makes sense it is not returned by the API, since a file submission could include multiple campaigns.

**Comment by cmspinto** [comment]
Can conform that it is working like this now. 

Picking the year of Campaign.StartDate in the Webservice to return the Campaings and picking the year when the Sample was taken in the sample. 


> I would say:
> 
>     * For `getCampaignRecords`, use the campaign.`startDate` as the basis for `year`
> 
>     * For `getSampleRecords`, use the sample.`date`  as the basis for `year`
> 
> 
> You could also use `startDate` for both, as it is unlikely that campaigns will cross years.

**Comment by peterdesmet** [comment]
I'm leaving this open until I can confirm https://github.com/ices-tools-dev/esas/issues/89#issuecomment-1158678203: typo is fixed (currently still there) and campaignID is not returned for fileSubmissions (currently all data removed, so cannot test)

**Comment by peterdesmet** [comment]
Still to do:

- [ ] Documentation: don't list `campaignID` as parameter of fileSubmissions
- [ ] Fix year queries for campaigns: https://esas.ices.dk/api/getCampaignRecords?year=1996
- [ ] Test year range queries for samples: https://esas.ices.dk/api/getSampleRecords?year=2020,2021

**Comment by peterdesmet** [comment]
Remaining issues addressed. Closing issue.
