### ISSUE TITLE
Review data model by ICES

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#9]
The ESAS data model as it currently stands is now up to date in the repository and **ready for review**. It is the result of discussions of the ESAS working group. You can see it as a [web page](https://ices-tools-dev.github.io/esas/tables/) or as [source files](https://github.com/ices-tools-dev/esas/tree/main/_data/table-schemas) (yaml files following the [Table Schema specs](https://specs.frictionlessdata.io/table-schema/)). Controlled vocabularies for the fields are described in `description`, with the actual values to validate against listed in `constraints > enum`. Example:

https://github.com/ices-tools-dev/esas/blob/00d94d1aa85f2af78b722995b34e31442507c736/_data/table-schemas/trips.yaml#L292-L305

3 fields have controlled vocabularies described elsewhere:

- [`platform_code`](https://github.com/ices-tools-dev/esas/blob/main/_data/vocabularies/platform_code.tsv)
- [`euring_species_code`](https://github.com/ices-tools-dev/esas/blob/main/_data/vocabularies/euring_species_code.tsv), also available as a [web page](https://ices-tools-dev.github.io/esas/species/)
- `observer1`, `observer2`, `observer3`: file not uploaded yet, pending decision in #6 

It would be good if this model is reviewed by the ICES @ices-tools-dev/data-and-information group, providing feedback on:

1. Suggestions to use it as a data exchange schema (i.e. the format to upload data to ICES), including flattening the schema (and at which stage)
2. Suggestions for existing controlled vocabularies (all vocabularies except for EURING codes are bespoke ESAS ones)
3. Does it the data model provide sufficient information to start creating a database model?

@neil-ices-dk @Osanna123 @pcrjoana @cmspinto: can you let us know when you would have time for this? @nicolasvanermen and me can answer questions if you have some. Please create separate issues per topic (e.g. suggested controlled vocab for specific field), so we can track decisions. Thanks!

**Comment by peterdesmet** [comment]
I have now created separate issues for all controlled vocabularies in https://github.com/ices-tools-dev/esas/milestone/1

**Comment by Osanna123** [comment]
I'd suggest adding a field 'country' to the table 'Trips' and 'tripkey' to the table 'Observations'

**Comment by peterdesmet** [comment]
Thanks, the two suggestions have been added as #43 and #44. Closing this issue.
