### ISSUE TITLE
File information

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-tools-dev/esas#90]
Currently this table is explained as "Campaigns that generated the data.", thus copy pasted from the Campaigns table. 
To be honest I have difficulaties explaining to data providers the actual use of this table, currently only holding two fields (data rights holder and country). So a concise clear explanation of this table would be nice.

**Comment by peterdesmet** [comment]
Updated (for all tables) in https://github.com/ices-tools-dev/esas/commit/29d9f3ef3cce4a9adb022bfb0b407c8ccbdf7ebe
