### ISSUE TITLE
Rights for reuploading files

### ISSUE THREAD

**Issue by peterdesmet** [ices-tools-dev/esas#91]
I have put now @nicolasvanermen  with rights for organization 200, so you should be able to re-upload files.

Question is, if a user upload the file, should the user be able to overwrite that file event do he does not have the right permissions for that organization?

_Originally posted by @cmspinto in https://github.com/ices-tools-dev/esas/issues/76#issuecomment-1158700337_

**Comment by nicolasvanermen** [comment]
Note that all test files have organisation 202, i.e. INBO. Still could not perform a resubmission...
"There was a problem updating the accession:-1, please contact accessions@ices.dk"
![image](https://user-images.githubusercontent.com/7381853/174618503-b3433a2c-8938-4119-9e3a-c7d8a8a6ea12.png)

**Comment by cmspinto** [comment]
Could we test (re)submission?
I want to avoid uploading test files to the to test the (re)submission, but I can do that. 
In the case of resubmission's have agree with @nicolasvanermen  that a user will always be able to overwrite a file that the user itself uploaded.
Right now in case of resubmission's, it's cheeking if you are the datarightholder for that organization, but we will make an exception in case it is the same user.

**Comment by nicolasvanermen** [comment]
indeed: see https://github.com/ices-tools-dev/esas/issues/92
