### ISSUE TITLE
Metadata Record

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-dev/esas#96]
Full metadata record: Add the list the data providers in the metadata record. 

- [x] 202 Research Institute for Nature and Forest (INBO)
- [x] 630 NIOZ Royal Netherlands Institute for Sea Research (NIOZ)
- [x] 1375 Joint Nature Conservation Committee, Aberdeen Office (JNCC)
- [ ] 1416 Norwegian Institute for Nature Research (NINA)
- [x] 2125 University College Cork (UCC)
- [x] 2299 Research and Technology Centre, Buesum (FTZ)
- [x] 2422 Wageningen Marine Research (Den Helder) (WMR)
- [x] 2827 Royal Society for the Protection of Birds (HQ) (RSPB)
- [x] 3269 Federal Agency for Nature Conservation (BfN)
- [x] 5045 Bureau Waardenburg BV (BUWA)
- [ ] 5123 Aarhus University, Department of Bioscience (BIOS)
- [x] 5440 Ornis Consult A/S
- [x] 5441 Institute of Avian Research
- [x] 5442 Dutch Seabird Group (NZG)
- [x] 5443 Portuguese Society for the Study of Birds (SPEA)
- [x] 5444 Cork Ecology

**Comment by peterdesmet** [comment]
Please write as

> View [full metadata]() for European Seabirds At Sea (ESAS).

**Comment by peterdesmet** [comment]
@nicolasvanermen can you indicate the institutes that are very likely to be included after first migration

**Comment by neil-ices-dk** [comment]
> Please write as
> 
> > View full metadata for European Seabirds At Sea (ESAS).

done

**Comment by nicolasvanermen** [comment]
I checked the institutes from which we have received explicit permission regarding the migration of their data to ICES Data Centre.  Also checked are the German data providers who have promised to submit their data themselves. Personally, however, I would wait until the end of september to compile a list based on the actual data migrations that have taken place by then.

**Comment by nicolasvanermen** [comment]
Just a question... How will the list of data providers be integrated in the current metadata record? Under what header?

**Comment by neil-ices-dk** [comment]
Hi @nicolasvanermen there are a number of ways to do it:

**option 1**
each data provider can be added as a 'point of contact' in the meta data record with roletype set as 'Originator'. This would require the following info from each data orginator: 
- organisation name
- individual name 
- email (can be a generic address)

**option 2**
we could add it in the text of the citation purpose of the meta record, although this is not really the intended use of that field

**Comment by peterdesmet** [comment]
@nicolasvanermen do you think it is a good time to give @neil-ices-dk the list of providers (org name, indiv name, email) for the metadata record or do you prefer to wait?

**Comment by nicolasvanermen** [comment]
Let's wait until the end of September for a final list!

**Comment by nicolasvanermen** [comment]
Now checked the DRH who's data are in the [folder](https://drive.google.com/drive/folders/147BaXPO9F8YVG-rLIgQqp_Tj7SJawtll)

**Comment by nicolasvanermen** [comment]
The list is completed (see checked boxes in the issue message on top), we will hold on to the Ornis Consult code. We will update the list the end of October.

**Comment by nicolasvanermen** [comment]
Good news, just checked the Cork Ecology box, who agreed with uploading the data as open access! Only NERI & NINA are now lagging behind, but this only a very small part of the total database.
