### ISSUE TITLE
Test deletion of file versus deletion data

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-tools-dev/esas#98]
scenario:

- user submits file with campaigns A & B
- user submits file with campaigns B & C, overwriting campaign B
- user deletes file with campaigns B & C

THEN

- only campaign A should stay in the database

**Comment by cmspinto** [comment]
I can perform the database cleaning if you want after running this test? 
I can confirm this should be what happens in the database.

**Comment by nicolasvanermen** [comment]
Wanted to test this, but couldn't access the Submissions page... How come? 
I uploaded a file with campaign 153 & 154, and one with campaigns 154 & 155. Campaign 154 was successfully overwritten. But due to the dead end I couldn't delete the second file to perform the test.

**Comment by nicolasvanermen** [comment]
Test was successful!
