### ISSUE TITLE
Clean application

### ISSUE THREAD

**Issue by nicolasvanermen** [ices-tools-dev/esas#99]
- [x] Delete all submitted files
- [x] Clean list of file screenings
- [x] Clean list of restricted data requests

**Comment by nicolasvanermen** [comment]
I noticed that, after deleting all my test files, that there are no more 'restricted data requests'.

**Comment by cmspinto** [comment]
Done, have removed all data from the database. 

Database is now completely empty and when inserting the files the filters in the inventory will also become available.
